# Test Cases
To properly test all functions several data sets are being loaded and investigated.

In [6]:
import impyte3
import pandas as pd

In [7]:
reload(impyte3)
imp = impyte3.Impyter()

## Titanic Data
From Kaggle Titanic Data Set.

In [8]:
reload(impyte3)
imp = impyte3.Impyter()
titanic = pd.read_csv("data/testdata/titanic_data.csv", low_memory=False)
imp.load_data(titanic)

In [9]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [10]:
_ = imp.impute(verbose=True)

Computing NaN-patterns first ...

Scoring Threshold             Classification                Regression
==========================================================================================
                              None                          None

Pattern: Label                Score                         Estimator
==========================================================================================
0: Cabin (*)                  0.000 (f1_macro)              RandomForestClassifier          imputed...
3: Age                        0.113 (r2)                    RandomForestRegressor           imputed...
4: Embarked (*)               0.000 (f1_macro)              RandomForestClassifier          imputed...


* Cabin: All the n_groups for individual classes are less than n_splits=5.
* Embarked: The least populated class in y has only 2 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.

In [11]:
titanic.drop("Cabin", axis=1, inplace=True)

In [13]:
imp.load_data(titanic)
_ = imp.get_summary()

In [14]:
imp.pattern()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Count
0,1,1,1,1,1,1,1,1,1,1,1,712
1,1,1,1,1,1,NaN,1,1,1,1,1,177
2,1,1,1,1,1,1,1,1,1,1,NaN,2

In [15]:
imp.get_data().head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [16]:
res = imp.impute(multi_nans=True)

Scoring Threshold             Classification                Regression
==========================================================================================
                              None                          None

Pattern: Label                Score                         Estimator
==========================================================================================
1: Age                        0.212 (r2)                    RandomForestRegressor           imputed...
2: Embarked (*)               0.000 (f1_macro)              RandomForestClassifier          imputed...


* Embarked: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.

In [17]:
res.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [19]:
imp2 = impyte3.Impyter(res)

In [20]:
imp2.pattern()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Count
0,1,1,1,1,1,1,1,1,1,1,1,891

## Sensoric Data

In [21]:
sensoric_data = pd.read_csv('data/testdata/pml-training.csv', low_memory=False)

In [29]:
reload(impyte3)
imp = impyte3.Impyter(sensoric_data)

In [30]:
summa = imp.get_summary()
summa

                          Complete  Missing Percentage  Unique
max_roll_belt                  406    19216    97.93 %     196
kurtosis_roll_forearm          406    19216    97.93 %     322
kurtosis_roll_belt             406    19216    97.93 %     397
kurtosis_picth_belt            406    19216    97.93 %     317
kurtosis_yaw_belt              406    19216    97.93 %       2
skewness_roll_belt             406    19216    97.93 %     395
skewness_roll_belt.1           406    19216    97.93 %     338
skewness_yaw_belt              406    19216    97.93 %       2
avg_yaw_dumbbell               406    19216    97.93 %     398
max_yaw_belt                   406    19216    97.93 %      68
min_roll_belt                  406    19216    97.93 %     185
min_pitch_belt                 406    19216    97.93 %      17
var_yaw_dumbbell               406    19216    97.93 %     392
stddev_yaw_dumbbell            406    19216    97.93 %     392
kurtosis_picth_forearm         406    19216    97.93 %     323
var_pitch_dumbbell             406    19216    97.93 %     392
stddev_pitch_dumbbell          406    19216    97.93 %     392
avg_pitch_dumbbell             406    19216    97.93 %     398
max_picth_belt                 406    19216    97.93 %      23
kurtosis_yaw_forearm           406    19216    97.93 %       2
min_roll_forearm               406    19216    97.93 %     270
skewness_pitch_forearm         406    19216    97.93 %     319
var_yaw_forearm                406    19216    97.93 %     323
stddev_yaw_forearm             406    19216    97.93 %     323
avg_yaw_forearm                406    19216    97.93 %     325
var_pitch_forearm              406    19216    97.93 %     325
stddev_pitch_forearm           406    19216    97.93 %     324
avg_pitch_forearm              406    19216    97.93 %     325
var_roll_forearm               406    19216    97.93 %     321
stddev_roll_forearm            406    19216    97.93 %     321
...                            ...      ...        ...     ...
stddev_yaw_belt                406    19216    97.93 %      59
avg_roll_dumbbell              406    19216    97.93 %     398
max_roll_arm                   406    19216    97.93 %     291
max_yaw_arm                    406    19216    97.93 %      52
amplitude_yaw_dumbbell         406    19216    97.93 %       3
amplitude_pitch_dumbbell       406    19216    97.93 %     384
amplitude_roll_dumbbell        406    19216    97.93 %     388
min_yaw_dumbbell               406    19216    97.93 %      73
min_pitch_dumbbell             406    19216    97.93 %     357
min_roll_dumbbell              406    19216    97.93 %     333
max_yaw_dumbbell               406    19216    97.93 %      73
max_picth_dumbbell             406    19216    97.93 %     340
max_roll_dumbbell              406    19216    97.93 %     339
skewness_yaw_dumbbell          406    19216    97.93 %       2
skewness_pitch_dumbbell        406    19216    97.93 %     402
max_picth_arm                  406    19216    97.93 %     264
skewness_roll_dumbbell         406    19216    97.93 %     401
kurtosis_picth_dumbbell        406    19216    97.93 %     401
kurtosis_roll_dumbbell         406    19216    97.93 %     398
amplitude_roll_belt            406    19216    97.93 %     149
amplitude_pitch_belt           406    19216    97.93 %      14
amplitude_yaw_belt             406    19216    97.93 %       4
amplitude_yaw_arm              406    19216    97.93 %      52
amplitude_pitch_arm            406    19216    97.93 %     295
amplitude_roll_arm             406    19216    97.93 %     307
var_total_accel_belt           406    19216    97.93 %      66
min_pitch_arm                  406    19216    97.93 %     291
min_roll_arm                   406    19216    97.93 %     279
kurtosis_yaw_dumbbell          406    19216    97.93 %       2
min_yaw_arm                    406    19216    97.93 %      39

[100 rows x 4 columns]

In [31]:
imp.pattern()

,Unnamed: 0,user_name,raw_timestamp_part_1,raw_timestamp_part_2,cvtd_timestamp,new_window,num_window,roll_belt,pitch_belt,yaw_belt,total_accel_belt,kurtosis_roll_belt,kurtosis_picth_belt,kurtosis_yaw_belt,skewness_roll_belt,skewness_roll_belt.1,skewness_yaw_belt,max_roll_belt,max_picth_belt,max_yaw_belt,min_roll_belt,min_pitch_belt,min_yaw_belt,amplitude_roll_belt,amplitude_pitch_belt,amplitude_yaw_belt,var_total_accel_belt,avg_roll_belt,stddev_roll_belt,var_roll_belt,avg_pitch_belt,stddev_pitch_belt,var_pitch_belt,avg_yaw_belt,stddev_yaw_belt,var_yaw_belt,gyros_belt_x,gyros_belt_y,gyros_belt_z,accel_belt_x,accel_belt_y,accel_belt_z,magnet_belt_x,magnet_belt_y,magnet_belt_z,roll_arm,pitch_arm,yaw_arm,total_accel_arm,var_accel_arm,avg_roll_arm,stddev_roll_arm,var_roll_arm,avg_pitch_arm,stddev_pitch_arm,var_pitch_arm,avg_yaw_arm,stddev_yaw_arm,var_yaw_arm,gyros_arm_x,gyros_arm_y,gyros_arm_z,accel_arm_x,accel_arm_y,accel_arm_z,magnet_arm_x,magnet_arm_y,magnet_arm_z,kurtosis_roll_arm,kurtosis_picth_arm,kurtosis_yaw_arm,skewness_roll_arm,skewness_pitch_arm,skewness_yaw_arm,max_roll_arm,max_picth_arm,max_yaw_arm,min_roll_arm,min_pitch_arm,min_yaw_arm,amplitude_roll_arm,amplitude_pitch_arm,amplitude_yaw_arm,roll_dumbbell,pitch_dumbbell,yaw_dumbbell,kurtosis_roll_dumbbell,kurtosis_picth_dumbbell,kurtosis_yaw_dumbbell,skewness_roll_dumbbell,skewness_pitch_dumbbell,skewness_yaw_dumbbell,max_roll_dumbbell,max_picth_dumbbell,max_yaw_dumbbell,min_roll_dumbbell,min_pitch_dumbbell,min_yaw_dumbbell,amplitude_roll_dumbbell,amplitude_pitch_dumbbell,amplitude_yaw_dumbbell,total_accel_dumbbell,var_accel_dumbbell,avg_roll_dumbbell,stddev_roll_dumbbell,var_roll_dumbbell,avg_pitch_dumbbell,stddev_pitch_dumbbell,var_pitch_dumbbell,avg_yaw_dumbbell,stddev_yaw_dumbbell,var_yaw_dumbbell,gyros_dumbbell_x,gyros_dumbbell_y,gyros_dumbbell_z,accel_dumbbell_x,accel_dumbbell_y,accel_dumbbell_z,magnet_dumbbell_x,magnet_dumbbell_y,magnet_dumbbell_z,roll_forearm,pitch_forearm,yaw_forearm,kurtosis_roll_forearm,kurtosis_picth_forearm,kurtosis_yaw_forearm,skewness_roll_forearm,skewness_pitch_forearm,skewness_yaw_forearm,max_roll_forearm,max_picth_forearm,max_yaw_forearm,min_roll_forearm,min_pitch_forearm,min_yaw_forearm,amplitude_roll_forearm,amplitude_pitch_forearm,amplitude_yaw_forearm,total_accel_forearm,var_accel_forearm,avg_roll_forearm,stddev_roll_forearm,var_roll_forearm,avg_pitch_forearm,stddev_pitch_forearm,var_pitch_forearm,avg_yaw_forearm,stddev_yaw_forearm,var_yaw_forearm,gyros_forearm_x,gyros_forearm_y,gyros_forearm_z,accel_forearm_x,accel_forearm_y,accel_forearm_z,magnet_forearm_x,magnet_forearm_y,magnet_forearm_z,classe,Count
0,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,19216
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,406

In [32]:
tmp2 = imp.pattern()

In [33]:
res = imp.impute(multi_nans=True)

Scoring Threshold             Classification                Regression
==========================================================================================
                              None                          None

Pattern: Label                Score                         Estimator
==========================================================================================

Multi nans
==========================================================================================
0: kurtosis_roll_belt (* 1)   0.000 (f1_macro)              RandomForestClassifier          imputed...
0: kurtosis_picth_belt (* 2)  0.000 (f1_macro)              RandomForestClassifier          imputed...
0: kurtosis_yaw_belt          1.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_roll_belt (* 3)   0.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_roll_belt.1 (* 4) 0.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_yaw_belt          1.000 (f1_macro)              RandomForestClassifier          imputed...
0: max_roll_belt              0.966 (r2)                    RandomForestRegressor           imputed...
0: max_picth_belt             0.930 (r2)                    RandomForestRegressor           imputed...
0: max_yaw_belt (* 5)         0.000 (f1_macro)              RandomForestClassifier          imputed...
0: min_roll_belt              0.912 (r2)                    RandomForestRegressor           imputed...
0: min_pitch_belt             0.977 (r2)                    RandomForestRegressor           imputed...
0: min_yaw_belt (* 6)         0.000 (f1_macro)              RandomForestClassifier          imputed...
0: amplitude_roll_belt        -122.151 (r2)                 RandomForestRegressor           imputed...
0: amplitude_pitch_belt       -0.718 (r2)                   RandomForestRegressor           imputed...
0: amplitude_yaw_belt (* 7)   0.000 (f1_macro)              RandomForestClassifier          imputed...
0: var_total_accel_belt       -19.618 (r2)                  RandomForestRegressor           imputed...
0: avg_roll_belt              0.988 (r2)                    RandomForestRegressor           imputed...
0: stddev_roll_belt           -0.215 (r2)                   RandomForestRegressor           imputed...
0: var_roll_belt              -2.759 (r2)                   RandomForestRegressor           imputed...
0: avg_pitch_belt             0.952 (r2)                    RandomForestRegressor           imputed...
0: stddev_pitch_belt          -0.073 (r2)                   RandomForestRegressor           imputed...
0: var_pitch_belt             -0.580 (r2)                   RandomForestRegressor           imputed...
0: avg_yaw_belt               0.968 (r2)                    RandomForestRegressor           imputed...
0: stddev_yaw_belt            -472.250 (r2)                 RandomForestRegressor           imputed...
0: var_yaw_belt               -810366.529 (r2)              RandomForestRegressor           imputed...
0: var_accel_arm              0.317 (r2)                    RandomForestRegressor           imputed...
0: avg_roll_arm               0.845 (r2)                    RandomForestRegressor           imputed...
0: stddev_roll_arm            -0.282 (r2)                   RandomForestRegressor           imputed...
0: var_roll_arm               -16.000 (r2)                  RandomForestRegressor           imputed...
0: avg_pitch_arm              0.584 (r2)                    RandomForestRegressor           imputed...
0: stddev_pitch_arm           0.290 (r2)                    RandomForestRegressor           imputed...
0: var_pitch_arm              -0.033 (r2)                   RandomForestRegressor           imputed...
0: avg_yaw_arm                0.661 (r2)                    RandomForestRegressor           imputed...
0: stddev_yaw_arm             -0.686 (r2)                   RandomForestRegressor           imputed...
0: var_yaw_arm                -2.419 (r2)                   RandomForestRegressor           imputed...
0: kurtosis_roll_arm (* 8)    0.000 (f1_macro)              RandomForestClassifier          imputed...
0: kurtosis_picth_arm (* 9)   0.000 (f1_macro)              RandomForestClassifier          imputed...
0: kurtosis_yaw_arm (* 10)    0.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_roll_arm (* 11)   0.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_pitch_arm (* 12)  0.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_yaw_arm (* 13)    0.000 (f1_macro)              RandomForestClassifier          imputed...
0: max_roll_arm               0.501 (r2)                    RandomForestRegressor           imputed...
0: max_picth_arm              0.545 (r2)                    RandomForestRegressor           imputed...
0: max_yaw_arm                0.462 (r2)                    RandomForestRegressor           imputed...
0: min_roll_arm               0.413 (r2)                    RandomForestRegressor           imputed...
0: min_pitch_arm              0.488 (r2)                    RandomForestRegressor           imputed...
0: min_yaw_arm                0.144 (r2)                    RandomForestRegressor           imputed...
0: amplitude_roll_arm         0.297 (r2)                    RandomForestRegressor           imputed...
0: amplitude_pitch_arm        0.178 (r2)                    RandomForestRegressor           imputed...
0: amplitude_yaw_arm          0.360 (r2)                    RandomForestRegressor           imputed...
0: kurtosis_roll_dumbbell (* 14)0.000 (f1_macro)              RandomForestClassifier          imputed...
0: kurtosis_picth_dumbbell (* 15)0.000 (f1_macro)              RandomForestClassifier          imputed...
0: kurtosis_yaw_dumbbell      1.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_roll_dumbbell (* 16)0.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_pitch_dumbbell (* 17)0.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_yaw_dumbbell      1.000 (f1_macro)              RandomForestClassifier          imputed...
0: max_roll_dumbbell          0.679 (r2)                    RandomForestRegressor           imputed...
0: max_picth_dumbbell         0.858 (r2)                    RandomForestRegressor           imputed...
0: max_yaw_dumbbell (* 18)    0.000 (f1_macro)              RandomForestClassifier          imputed...
0: min_roll_dumbbell          0.290 (r2)                    RandomForestRegressor           imputed...
0: min_pitch_dumbbell         0.732 (r2)                    RandomForestRegressor           imputed...
0: min_yaw_dumbbell (* 19)    0.000 (f1_macro)              RandomForestClassifier          imputed...
0: amplitude_roll_dumbbell    0.258 (r2)                    RandomForestRegressor           imputed...
0: amplitude_pitch_dumbbell   0.352 (r2)                    RandomForestRegressor           imputed...
0: amplitude_yaw_dumbbell (* 20)0.000 (f1_macro)              RandomForestClassifier          imputed...
0: var_accel_dumbbell         0.086 (r2)                    RandomForestRegressor           imputed...
0: avg_roll_dumbbell          0.635 (r2)                    RandomForestRegressor           imputed...
0: stddev_roll_dumbbell       0.132 (r2)                    RandomForestRegressor           imputed...
0: var_roll_dumbbell          0.008 (r2)                    RandomForestRegressor           imputed...
0: avg_pitch_dumbbell         0.726 (r2)                    RandomForestRegressor           imputed...
0: stddev_pitch_dumbbell      0.327 (r2)                    RandomForestRegressor           imputed...
0: var_pitch_dumbbell         0.026 (r2)                    RandomForestRegressor           imputed...
0: avg_yaw_dumbbell           0.861 (r2)                    RandomForestRegressor           imputed...
0: stddev_yaw_dumbbell        0.315 (r2)                    RandomForestRegressor           imputed...
0: var_yaw_dumbbell           -0.168 (r2)                   RandomForestRegressor           imputed...
0: kurtosis_roll_forearm (* 21)0.000 (f1_macro)              RandomForestClassifier          imputed...
0: kurtosis_picth_forearm (* 22)0.000 (f1_macro)              RandomForestClassifier          imputed...
0: kurtosis_yaw_forearm       1.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_roll_forearm (* 23)0.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_pitch_forearm (* 24)0.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_yaw_forearm       1.000 (f1_macro)              RandomForestClassifier          imputed...
0: max_roll_forearm           0.553 (r2)                    RandomForestRegressor           imputed...
0: max_picth_forearm          0.484 (r2)                    RandomForestRegressor           imputed...
0: max_yaw_forearm (* 25)     0.000 (f1_macro)              RandomForestClassifier          imputed...
0: min_roll_forearm           0.183 (r2)                    RandomForestRegressor           imputed...
0: min_pitch_forearm          0.436 (r2)                    RandomForestRegressor           imputed...
0: min_yaw_forearm (* 26)     0.000 (f1_macro)              RandomForestClassifier          imputed...
0: amplitude_roll_forearm     -0.018 (r2)                   RandomForestRegressor           imputed...
0: amplitude_pitch_forearm    0.436 (r2)                    RandomForestRegressor           imputed...
0: amplitude_yaw_forearm      0.996 (f1_macro)              RandomForestClassifier          imputed...
0: var_accel_forearm          -0.541 (r2)                   RandomForestRegressor           imputed...
0: avg_roll_forearm           0.365 (r2)                    RandomForestRegressor           imputed...
0: stddev_roll_forearm        0.210 (r2)                    RandomForestRegressor           imputed...
0: var_roll_forearm           0.179 (r2)                    RandomForestRegressor           imputed...
0: avg_pitch_forearm          0.497 (r2)                    RandomForestRegressor           imputed...
0: stddev_pitch_forearm       -0.023 (r2)                   RandomForestRegressor           imputed...
0: var_pitch_forearm          -0.998 (r2)                   RandomForestRegressor           imputed...
0: avg_yaw_forearm            0.520 (r2)                    RandomForestRegressor           imputed...
0: stddev_yaw_forearm         0.370 (r2)                    RandomForestRegressor           imputed...
0: var_yaw_forearm            0.200 (r2)                    RandomForestRegressor           imputed...


* (1)kurtosis_roll_belt: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (2)kurtosis_picth_belt: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (3)skewness_roll_belt: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (4)skewness_roll_belt.1: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (5)max_yaw_belt: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (6)min_yaw_belt: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (7)amplitude_yaw_belt: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
* (8)kurtosis_roll_arm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (9)kurtosis_picth_arm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (10)kurtosis_yaw_arm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (11)skewness_roll_arm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (12)skewness_pitch_arm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (13)skewness_yaw_arm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (14)kurtosis_roll_dumbbell: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (15)kurtosis_picth_dumbbell: All the n_groups for individual classes are less than n_splits=5.
* (16)skewness_roll_dumbbell: All the n_groups for individual classes are less than n_splits=5.
* (17)skewness_pitch_dumbbell: All the n_groups for individual classes are less than n_splits=5.
* (18)max_yaw_dumbbell: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (19)min_yaw_dumbbell: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (20)amplitude_yaw_dumbbell: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
* (21)kurtosis_roll_forearm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (22)kurtosis_picth_forearm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (23)skewness_roll_forearm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (24)skewness_pitch_forearm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (25)max_yaw_forearm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (26)min_yaw_forearm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.

In [35]:
imp2 = impyte3.Impyter(res)

In [36]:
imp2.pattern()

,Unnamed: 0,user_name,raw_timestamp_part_1,raw_timestamp_part_2,cvtd_timestamp,new_window,num_window,roll_belt,pitch_belt,yaw_belt,total_accel_belt,kurtosis_roll_belt,kurtosis_picth_belt,kurtosis_yaw_belt,skewness_roll_belt,skewness_roll_belt.1,skewness_yaw_belt,max_roll_belt,max_picth_belt,max_yaw_belt,min_roll_belt,min_pitch_belt,min_yaw_belt,amplitude_roll_belt,amplitude_pitch_belt,amplitude_yaw_belt,var_total_accel_belt,avg_roll_belt,stddev_roll_belt,var_roll_belt,avg_pitch_belt,stddev_pitch_belt,var_pitch_belt,avg_yaw_belt,stddev_yaw_belt,var_yaw_belt,gyros_belt_x,gyros_belt_y,gyros_belt_z,accel_belt_x,accel_belt_y,accel_belt_z,magnet_belt_x,magnet_belt_y,magnet_belt_z,roll_arm,pitch_arm,yaw_arm,total_accel_arm,var_accel_arm,avg_roll_arm,stddev_roll_arm,var_roll_arm,avg_pitch_arm,stddev_pitch_arm,var_pitch_arm,avg_yaw_arm,stddev_yaw_arm,var_yaw_arm,gyros_arm_x,gyros_arm_y,gyros_arm_z,accel_arm_x,accel_arm_y,accel_arm_z,magnet_arm_x,magnet_arm_y,magnet_arm_z,kurtosis_roll_arm,kurtosis_picth_arm,kurtosis_yaw_arm,skewness_roll_arm,skewness_pitch_arm,skewness_yaw_arm,max_roll_arm,max_picth_arm,max_yaw_arm,min_roll_arm,min_pitch_arm,min_yaw_arm,amplitude_roll_arm,amplitude_pitch_arm,amplitude_yaw_arm,roll_dumbbell,pitch_dumbbell,yaw_dumbbell,kurtosis_roll_dumbbell,kurtosis_picth_dumbbell,kurtosis_yaw_dumbbell,skewness_roll_dumbbell,skewness_pitch_dumbbell,skewness_yaw_dumbbell,max_roll_dumbbell,max_picth_dumbbell,max_yaw_dumbbell,min_roll_dumbbell,min_pitch_dumbbell,min_yaw_dumbbell,amplitude_roll_dumbbell,amplitude_pitch_dumbbell,amplitude_yaw_dumbbell,total_accel_dumbbell,var_accel_dumbbell,avg_roll_dumbbell,stddev_roll_dumbbell,var_roll_dumbbell,avg_pitch_dumbbell,stddev_pitch_dumbbell,var_pitch_dumbbell,avg_yaw_dumbbell,stddev_yaw_dumbbell,var_yaw_dumbbell,gyros_dumbbell_x,gyros_dumbbell_y,gyros_dumbbell_z,accel_dumbbell_x,accel_dumbbell_y,accel_dumbbell_z,magnet_dumbbell_x,magnet_dumbbell_y,magnet_dumbbell_z,roll_forearm,pitch_forearm,yaw_forearm,kurtosis_roll_forearm,kurtosis_picth_forearm,kurtosis_yaw_forearm,skewness_roll_forearm,skewness_pitch_forearm,skewness_yaw_forearm,max_roll_forearm,max_picth_forearm,max_yaw_forearm,min_roll_forearm,min_pitch_forearm,min_yaw_forearm,amplitude_roll_forearm,amplitude_pitch_forearm,amplitude_yaw_forearm,total_accel_forearm,var_accel_forearm,avg_roll_forearm,stddev_roll_forearm,var_roll_forearm,avg_pitch_forearm,stddev_pitch_forearm,var_pitch_forearm,avg_yaw_forearm,stddev_yaw_forearm,var_yaw_forearm,gyros_forearm_x,gyros_forearm_y,gyros_forearm_z,accel_forearm_x,accel_forearm_y,accel_forearm_z,magnet_forearm_x,magnet_forearm_y,magnet_forearm_z,classe,Count
0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,19622

In [37]:
!ls data/testdata

KaggleV2-May-2016.csv           matched_Building_Complaints.csv
customers.csv                   pml-training.csv
file_safety_complaints_fair.csv student-data.csv
housing.csv                     titanic_data.csv

In [38]:
import impyte

In [39]:
reload(impyte)

In [40]:
customer_data = pd.read_csv('data/testdata/file_safety_complaints_fair.csv')

In [41]:
#customer_data.drop(["Address", "Closest Address", "Location"], axis=1, inplace=True)

In [42]:
imp3 = impyte3.Impyter(customer_data[:1000])

In [43]:
imp3.pattern()

,EAS,Complaint Item Type Description,Address,Zipcode,Battalion,Station Area,Received Date,Entry Date,Disposition,Disposition Date,Neighborhood District,Location,Longitude,Latitude,LonRad,LatRad,Closest Address,Score,Count_of_complaints_per_each_EAS,Count
0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,801
1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,74
2,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,72
3,1,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,39
4,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,7
5,1,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,5
6,NaN,1,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,2

In [45]:
imp3.get_summary()

                                  Complete  Missing Percentage  Unique
Battalion                              998        2     0.20 %      11
Station Area                           993        7     0.70 %      39
EAS                                    991        9     0.90 %     431
Closest Address                        991        9     0.90 %     431
Count_of_complaints_per_each_EAS       991        9     0.90 %      21
Score                                  991        9     0.90 %      15
Disposition Date                       889      111    11.10 %     658
Disposition                            887      113    11.30 %       8

In [46]:
imp3.impute(multi_nans=True)

Scoring Threshold             Classification                Regression
==========================================================================================
                              None                          None

Pattern: Label                Score                         Estimator
==========================================================================================
1: Disposition (* 1)          0.000 (f1_macro)              RandomForestClassifier          imputed...
2: Disposition Date (* 2)     0.000 (f1_macro)              RandomForestClassifier          imputed...
5: Station Area (* 3)         0.000 (f1_macro)              RandomForestClassifier          imputed...

Multi nans
==========================================================================================
3: Disposition (* 4)          0.000 (f1_macro)              RandomForestClassifier          imputed...
3: Disposition Date (* 5)     0.000 (f1_macro)              RandomForestClassifier          imputed...
4: EAS                        0.444 (r2)                    RandomForestRegressor           imputed...
4: Closest Address (* 6)      0.000 (f1_macro)              RandomForestClassifier          imputed...
4: Score                      0.304 (r2)                    RandomForestRegressor           imputed...
4: Count_of_complaints_per_each_EAS0.754 (r2)                    RandomForestRegressor           imputed...
6: EAS                        0.416 (r2)                    RandomForestRegressor           imputed...
6: Battalion (* 7)            0.000 (f1_macro)              RandomForestClassifier          imputed...
6: Station Area (* 8)         0.000 (f1_macro)              RandomForestClassifier          imputed...
6: Closest Address (* 9)      0.000 (f1_macro)              RandomForestClassifier          imputed...
6: Score                      0.327 (r2)                    RandomForestRegressor           imputed...
6: Count_of_complaints_per_each_EAS0.750 (r2)                    RandomForestRegressor           imputed...


* (1)Disposition: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (2)Disposition Date: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (3)Station Area: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (4)Disposition: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (5)Disposition Date: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (6)Closest Address: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (7)Battalion: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
* (8)Station Area: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (9)Closest Address: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.

,EAS,Complaint Item Type Description,Address,Zipcode,Battalion,Station Area,Received Date,Entry Date,Disposition,Disposition Date,Neighborhood District,Location,Longitude,Latitude,LonRad,LatRad,Closest Address,Score,Count_of_complaints_per_each_EAS
0,281694.0,uncategorized complaint,460 Ellis St,94102.0,2,3,8/4/05,8/4/05,condition corrected,9/20/05,Tenderloin,"(37.7849959400297, -122.41382465)",-122.413825,37.784996,-2.136524,0.659473,460 ELLIS ST,96.0,1.0
1,304879.0,alarm systems,3215 Clement St,94121.0,7,34,10/31/11,10/31/11,condition corrected,10/31/11,Outer Richmond,"(37.7813616200296, -122.49378054)",-122.493780,37.781362,-2.137920,0.659409,3215 CLEMENT ST,97.0,3.0
2,296558.0,operating without a permit,705 Divisadero St,94117.0,5,21,1/28/13,1/28/13,condition corrected,1/28/13,Hayes Valley,"(37.7761620400297, -122.43834325)",-122.438343,37.776162,-2.136952,0.659318,705 DIVISADERO ST,97.0,1.0
3,281709.0,uncategorized complaint,372 - 376 Ellis St,94102.0,3,1,5/25/05,5/31/05,condition corrected,3/21/06,Tenderloin,"(37.7852057000297, -122.41238036)",-122.412380,37.785206,-2.136499,0.659476,376 ELLIS ST,90.0,25.0
4,403215.0,uncategorized complaint,228 Duncan St,94131.0,6,11,11/29/05,11/29/05,violation issued,11/29/05,Noe Valley,"(37.7464460500297, -122.42541757)",-122.425418,37.746446,-2.136727,0.658800,228 DUNCAN ST,96.0,17.0
5,458457.0,uncategorized complaint,843 - 855 Clay St,94108.0,1,2,1/19/06,1/19/06,violation issued,1/19/06,Chinatown,"(37.7939533600297, -122.40720213)",-122.407202,37.793953,-2.136409,0.659629,855 CLAY ST,90.0,6.0
6,345881.0,alarm systems,470 Collingwood St,94114.0,6,24,10/15/15,10/15/15,condition corrected,11/13/15,Noe Valley,"(37.7548629900296, -122.43586366)",-122.435864,37.754863,-2.136909,0.658947,470 COLLINGWOOD ST,97.0,2.0
7,281709.0,uncategorized complaint,372 - 376 Ellis St,94102.0,3,1,1/28/10,1/29/10,condition corrected,3/19/10,Tenderloin,"(37.7852057000297, -122.41238036)",-122.412380,37.785206,-2.136499,0.659476,376 ELLIS ST,90.0,25.0
8,374493.0,uncategorized complaint,1464 Davidson Ave,94124.0,10,25,10/5/12,10/5/12,violation issued,10/5/12,Bayview Hunters Point,"(37.7444246000296, -122.3889812)",-122.388981,37.744425,-2.136091,0.658764,1461 DAVIDSON AVE,91.0,3.0
9,281691.0,alarm systems,434 Ellis St,94102.0,2,3,6/5/12,6/5/12,condition corrected,6/5/12,Tenderloin,"(37.7850429700297, -122.41345523)",-122.413455,37.785043,-2.136518,0.659473,434 ELLIS ST,96.0,1.0
10,304251.0,uncategorized complaint,1541 Clement St,94118.0,7,31,2/14/14,2/14/14,condition corrected,2/14/14,Outer Richmond,"(37.7822133200297, -122.47592858)",-122.475929,37.782213,-2.137608,0.659424,1541 CLEMENT ST,97.0,2.0
11,360495.0,alarm systems,65 Dorland St,94110.0,2,7,12/1/11,12/1/11,condition corrected,12/1/11,Mission,"(37.7620309300297, -122.42527614)",-122.425276,37.762031,-2.136724,0.659072,65 DORLAND ST,96.0,1.0
12,441049.0,fire escape,1440 - 1442 Clement St,94118.0,7,31,6/29/17,6/29/17,condition corrected,1/7/09,Outer Richmond,"(37.7827289900297, -122.47487392)",-122.474874,37.782729,-2.137590,0.659433,1442 CLEMENT ST,90.0,7.0
13,458444.0,uncategorized complaint,817 - 825 Clay St,94108.0,1,2,2/8/16,2/8/16,violation issued,2/8/16,Chinatown,"(37.7940541500297, -122.40665655)",-122.406657,37.794054,-2.136399,0.659631,825 CLAY ST,90.0,4.0
14,458506.0,sprinkler/standpipe systems,678 - 692 Commercial St,94111.0,1,13,5/24/16,5/24/16,condition corrected,9/8/05,Chinatown,"(37.7942173000297, -122.40438863)",-122.404389,37.794217,-2.136360,0.659634,692 COMMERCIAL ST,95.0,13.0
15,421568.0,alarm systems,852 - 854 Clay St,94108.0,1,2,12/9/08,12/9/08,condition corrected,12/9/08,Chinatown,"(37.7942876800297, -122.40739823)",-122.407398,37.794288,-2.136412,0.659635,854 CLAY ST,90.0,9.0
16,393093.0,weeds and grass,97 Delta St,94134.0,9,44,8/8/05,8/9/05,condition corrected,1/7/15,Visitacion Valley,"(37.7180429500296, -122.40699092)",-122.406991,37.718043,-2.136405,0.658304,97 DELTA ST,96.0,3.0
17,458502.0,alarm systems,771 - 783 Clay St,94108.0,1,13,7/14/10,7/14/10,condition corrected,7/14/10,Chinatown,"(37.7941499400297, -122.40594759)",-122.405948,37.794150,-2.136387,0.659632,783 CLAY ST,90.0,6.0
18,410352.0,blocked exits,17 Edgar Ave,94112.0,9,15,4/28/11,4/28/11,condition corrected,4/28/11,Oceanview/Merced/Ingleside,"(37.7209074800296, -122.45240727)",-122.452407,37.720907,-2.137198,0.658354,17 EDGAR AVE,96.0,1.0
19,365485.0,alarm systems,436 - 438 Clementina St,94103.0,3,1,8/24/10,8/24/10,condition corrected,8/24/10,South of Market,"(37.7801204800297, -122.40493606)",-122.404936,37.780120,-2.136369,0.659387,436 CLEMENTINA ST,95.0,2.0
20,280681.0,sprinkler/standpipe systems,1271 California St,94109.0,1,41,10/8/15,10/8/15,condition corrected,1/6/16,Nob Hill,"(37.7910486800297, -122.41518597)",-122.415186,37.791049,-2.136548,0.659578,1271 CALIFORNIA ST,97.0,1.0
21,456506.0,alarm systems,28 Cyril Magnin St,94102.0,3,1,6/22/10,6/22/10,condition corrected,6/22/10,Tenderloin,"(37.7848850000297, -122.40814882)",-122.408149,37.784885,-2.136425,0.659471,28 CYRIL MAGNIN ST,97.0,2.0
22,343257.0,alarm systems,2 Diamond St,94114.0,2,6,4/20/15,4/20/15,condition corrected,5/5/15,Castro/Upper Market,"(37.7621528200296, -122.43749944)",-122.437499,37.762153,-2.136937,0.659074,2 DIAMOND ST,96.0,5.0
23,458506.0,blocked exits,678 - 692 Commercial St,94111.0,1,13,5/24/16,5/24/16,condition corrected,3/23/09,Chinatown,"(37.7942173000297, -122.40438863)",-122.404389,37.794217,-2.136360,0.659634,692 COMMERCIAL ST,95.0,13.0
24,458502.0,alarm systems,771 - 783 Clay St,94108.0,1,13,1/15/16,1/15/16,condition corrected,12/3/12,Chinatown,"(37.7941499400297, -122.40594759)",-122.405948,37.794150,-2.136387,0.659632,783 CLAY ST,90.0,6.0
25,445629.0,alarm systems,2913 - 2917 Clement St,94121.0,7,14,8/24/10,8/25/10,condition corrected,8/25/10,Outer Richmond,"(37.7815065500297, -122.49056692)",-122.490567,37.781507,-2.137864,0.659412,2917 CLEMENT ST,90.0,3.0
26,365287.0,alarm systems,744 - 746 Clementina St,94103.0,2,36,3/10/09,3/10/09,condition corrected,3/10/09,South of Market,"(37.7749434000297, -122.41149632)",-122.411496,37.774943,-2.136484,0.659297,744 CLEMENTINA ST,95.0,8.0
27,421577.0,alarm systems,1425 - 1427 Clay St,94109.0,1,41,9/25/07,9/25/07,condition corrected,2/20/08,Nob Hill,"(37.7926973300297, -122.41655056)",-122.416551,37.792697,-2.136572,0.659607,1427 CLAY ST,90.0,5.0
28,281725.0,sprinkler/standpipe systems,174 Ellis St,94102.0,3,1,8/13/15,8/13/15,condition corrected,5/13/15,Tenderloin,"(37.7856298300297, -122.40905197)",-122.409052,37.785630,-2.136441,0.659484,174 ELLIS ST,96.0,7.0
29,281730.0,alarm systems,124 - 140 Ellis St,94102.0,3,1,4/28/15,4/28/15,condition corrected,5/13/15,Tenderloin,"(37.7857238200297, -122.40851249)",-122.408513,37.785724,-2.136432,0.659485,140 ELLIS ST,90.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,445157.0,blocked exits,1226 - 1230 Grant Ave,94133.0,1,2,6/6/05,6/6/05,condition corrected,8/12/05,North Beach,"(37.7984315500296, -122.40695306)",-122.406953,37.798432,-2.136404,0.659707,1230 GRANT AVE,90.0,10.0
971,422345.0,alarm systems,1745 - 1751 Market St,94103.0,2,36,6/6/05,6/6/05,condition corrected,8/24/05,Mission,"(37.7718745200296, -122.42286566)",-122.422866,37.771875,-2.136682,0.659244,1751 MARKET ST,90.0,5.0
972,293533.0,alarm systems,300 Arguello Blvd,94118.0,7,10,6/6/05,6/6/05,condition corrected,6/6/05,Presidio Heights,"(37.7855392900297, -122.45879306)",-122.458793,37.785539,-2.137309,0.659482,300 ARGUELLO BLVD,97.0,4.0
973,280814.0,alarm systems,114 Sansome St,94104.0,1,13,6/6/05,6/6/05,condition corrected,7/19/05,Financial District/South Beach,"(37.7914995200297, -122.40045031)",-122.400450,37.791500,-2.136291,0.659586,114 SANSOME ST,97.0,3.0
974,446886.0,uncategorized complaint,445 - 447 Sutter St,94108.0,1,1,6/6/05,6/6/05,condition corrected,6/22/05,Financial District/South Beach,"(37.7890310200297, -122.40785854)",-122.407859,37.789031,-2.136420,0.659543,447 SUTTER ST,90.0,2.0
975,353834.0,extinguishers,300 Monterey Blvd,94131.0,9,15,6/6/05,6/6/05,condition corrected,11/20/08,West of Twin Peaks,"(37.7318107900296, -122.44233844)",-122.442338,37.731811,-2.137022,0.658544,300 MONTEREY BLVD,97.0,1.0
976,461806.0,combustible materials,380 - 386 Ellis St,94102.0,3,1,6/6/05,6/7/05,condition corrected,6/7/05,Tenderloin,"(37.7851215100297, -122.41249478)",-122.412495,37.785122,-2.136501,0.659475,386 ELLIS ST,90.0,2.0
977,448738.0,alarm systems,201 - 209 Post St,94108.0,1,1,6/7/05,6/7/05,condition corrected,6/8/05,Financial District/South Beach,"(37.7884065700297, -122.40541374)",-122.405414,37.788407,-2.136377,0.659532,209 POST ST,90.0,3.0
978,430904.0,blocked exits,427 - 431 Hickory St,94102.0,2,36,6/7/05,6/7/05,condition corrected,9/9/05,Hayes Valley,"(37.7747880200297, -122.42648711)",-122.426487,37.774788,-2.136745,0.659294,431 HICKORY ST,90.0,2.0
979,478999.0,uncategorized complaint,100 Brannan St,94107.0,3,35,6/7/05,6/7/05,violation issued,6/7/05,Financial District/South Beach,"(37.7846052000297, -122.3886494)",-122.388649,37.784605,-2.136085,0.659466,149 BRANNAN ST,83.0,2.0
980,483984.0,combustible materials,3495 - 3499 16th St,94114.0,2,6,6/7/05,6/7/05,condition corrected,6/22/05,Castro/Upper Market,"(37.7641525100297, -122.4306653)",-122.430665,37.764153,-2.136818,0.659109,3499 16TH ST,90.0,4.0
981,448567.0,alarm systems,2445 - 2447 Mariposa St,94110.0,2,7,6/7/05,6/7/05,condition corrected,6/7/05,Potrero Hill,"(37.7627266400296, -122.40778258)",-122.407783,37.762727,-2.136419,0.659084,2447 MARIPOSA ST,90.0,2.0
982,421679.0,alarm systems,481 - 485 Eddy St,94102.0,2,3,6/8/05,6/8/05,condition corrected,7/7/05,Tenderloin,"(37.7833498500297, -122.41550391)",-122.415504,37.783350,-2.136554,0.659444,485 EDDY ST,90.0,4.0
983,479330.0,uncategorized complaint,555 Jackson St,94111.0,1,13,6/8/05,6/8/05,condition corrected,7/7/05,Chinatown,"(37.7959477500297, -122.40476651)",-122.404766,37.795948,-2.136366,0.659664,555 JACKSON ST,97.0,2.0
984,457999.0,uncategorized complaint,735 - 745 Battery St,94111.0,1,13,6/8/05,6/8/05,condition corrected,6/27/05,Financial District/South Beach,"(37.7981481900297, -122.4013766)",-122.401377,37.798148,-2.136307,0.659702,745 BATTERY ST,90.0,1.0
985,280131.0,alarm systems,1539 Clay St,94109.0,1,41,6/9/05,6/10/05,condition corrected,1/7/09,Nob Hill,"(37.7924655900297, -122.41836654)",-122.418367,37.792466,-2.136604,0.659603,1539 CLAY ST,96.0,7.0
986,365755.0,operating without a permit,836 Harrison St,94107.0,3,8,6/9/05,6/10/05,condition corrected,3/1/06,South of Market,"(37.7802199500297, -122.40075068)",-122.400751,37.780220,-2.136296,0.659389,836 HARRISON ST,97.0,1.0
987,281428.0,alarm systems,642 Jones St,94102.0,1,3,6/9/05,6/10/05,condition corrected,1/3/06,Tenderloin,"(37.7873466000297, -122.41300992)",-122.413010,37.787347,-2.136510,0.659514,642 JONES ST,96.0,8.0
988,458860.0,blocked exits,2250 - 2252 Union St,94123.0,4,16,6/9/05,6/10/05,condition corrected,6/21/05,Marina,"(37.7972613000297, -122.43639)",-122.436390,37.797261,-2.136918,0.659687,2252 UNION ST,90.0,2.0
989,281791.0,alarm systems,345 Jones St,94102.0,2,3,6/9/05,6/9/05,condition corrected,7/28/05,Tenderloin,"(37.7845408400296, -122.41298929)",-122.412989,37.784541,-2.136510,0.659465,345 JONES ST,96.0,6.0
990,279099.0,alarm systems,728 Pacific Ave,94133.0,1,2,6/10/05,6/16/05,condition corrected,2/8/06,Chinatown,"(37.7970928900297, -122.40746696)",-122.407467,37.797093,-2.136413,0.659684,728 PACIFIC AVE,97.0,18.0
991,357645.0,blocked exits,25 Guerrero St,94103.0,2,36,6/10/05,6/13/05,condition corrected,6/10/05,Mission,"(37.7704428700296, -122.42436868)",-122.424369,37.770443,-2.136708,0.659219,25 GUERRERO ST,97.0,6.0
992,443305.0,alarm systems,601 - 617 Laguna St,94102.0,2,5,6/10/05,6/15/05,condition corrected,7/7/05,Hayes Valley,"(37.7767280200297, -122.42655043)",-122.426550,37.776728,-2.136746,0.659328,617 LAGUNA ST,90.0,3.0
993,450319.0,alarm systems,124 - 126 Turk St,94102.0,3,1,6/10/05,6/15/05,condition corrected,6/21/05,Tenderloin,"(37.7833907700297, -122.41136072)",-122.411361,37.783391,-2.136481,0.659445,126 TURK ST,90.0,6.0
994,307271.0,alarm systems,422 09th Ave,94118.0,7,31,6/10/05,6/15/05,condition corrected,7/25/05,Inner Richmond,"(37.7803063400297, -122.4671252)",-122.467125,37.780306,-2.137455,0.659391,422 09TH AVE,96.0,4.0
995,281791.0,roof access,345 Jones St,94102.0,2,3,6/10/05,6/15/05,condition corrected,7/7/05,Tenderloin,"(37.7845408400296, -122.41298929)",-122.412989,37.784541,-2.136510,0.659465,345 JONES ST,96.0,6.0
996,484493.0,alarm systems,7046 Geary Blvd,94121.0,7,34,6/10/05,6/15/05,condition corrected,9/30/05,Outer Richmond,"(37.7799166400297, -122.49520699)",-122.495207,37.779917,-2.137945,0.659384,7046 GEARY BLVD,97.0,1.0
997,281823.0,uncategorized complaint,300 Hyde St,94109.0,2,3,6/10/05,6/10/05,violation issued,6/10/05,Tenderloin,"(37.7837515500297, -122.41574005)",-122.415740,37.783752,-2.136558,0.659451,300 HYDE ST,96.0,9.0
998,281823.0,uncategorized complaint,300 Hyde St,94109.0,2,3,6/10/05,6/10/05,violation issued,6/10/05,Tenderloin,"(37.7837515500297, -122.41574005)",-122.415740,37.783752,-2.136558,0.659451,300 HYDE ST,96.0,9.0
999,357645.0,uncategorized complaint,25 Guerrero St,94103.0,2,36,6/10/05,6/10/05,violation issued,6/10/05,Mission,"(37.7704428700296, -122.42436868)",-122.424369,37.770443,-2.136708,0.659219,25 GUERRERO ST,97.0,6.0

In [47]:
res = imp3.get_result()

In [48]:
imp4 = impyte3.Impyter(res)
imp4.pattern()

,EAS,Complaint Item Type Description,Address,Zipcode,Battalion,Station Area,Received Date,Entry Date,Disposition,Disposition Date,Neighborhood District,Location,Longitude,Latitude,LonRad,LatRad,Closest Address,Score,Count_of_complaints_per_each_EAS,Count
0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1000

### Fire Cases

In [49]:
import impyte
import pandas as pd

In [50]:
imp5 = impyte3.Impyter(pd.read_csv("data/testdata/matched_Building_Complaints.csv", low_memory=False))

In [51]:
imp5.pattern()

,Unnamed: 0,Complaint Number,Date Filed,Block,Lot,Street Number,Street Name,Street Suffix,Unit,Complaint Description,Status,NOV Type,Receiving Division,Assigned Division,Date 1st NOV Issued,Date 2nd NOV Issued,Date Referred to City Attorney,Director Hearing Date,Last Inspection Date,Date Abated,Closed Date,Neighborhoods - Analysis Boundaries,Supervisor District,Zipcode,Location,Longitude,Latitude,Address,LonRad,LatRad,EAS,Closest Address,Score,Count
0,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,43965
1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,36499
2,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,21347
3,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,14857
4,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,13815
5,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,12489
6,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,7396
7,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,7120
8,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,4224
9,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,3639
10,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,3601
11,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,3470
12,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,3052
13,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,2926
14,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,2581
15,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2272
16,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1954
17,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1912
18,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1888
19,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1634
20,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1547
21,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1511
22,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1469
23,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1220
24,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1075
25,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1068
26,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1020
27,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,907
28,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,814
29,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,766
30,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,614
31,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,601
32,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,562
33,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,499
34,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,431
35,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,364
36,1,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,341
37,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,301
38,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,282
39,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,280
40,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,269
41,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,258
42,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,254
43,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,253
44,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,236
45,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,231
46,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,217
47,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,214
48,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,211
49,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,198
50,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,189
51,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,160
52,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,155
53,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,151
54,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,150
55,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,141
56,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,140
57,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,132
58,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,130
59,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,124
60,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,123
61,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,110
62,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,108
63,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,106
64,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,105
65,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,101
66,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,99
67,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,95
68,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,95
69,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,91
70,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,89
71,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,87
72,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,86
73,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,86
74,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,85
75,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,80
76,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,78
77,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,78
78,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,76
79,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,76
80,1,1,1,1,1,1,1,NaN,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,74
81,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,1,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,68
82,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,67
83,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,66
84,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,66
85,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,64
86,1,1,1,1,1,1,1,NaN,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,62
87,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,61
88,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,60
89,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,60
90,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,56
91,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,56
92,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,53
93,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,52
94,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,52
95,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,51
96,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,46
97,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,45
98,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,44
99,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,44
100,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,43
101,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,39
102,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,39
103,1,1,1,1,1,1,1,NaN,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,38
104,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,36
105,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,35
106,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,35
107,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,35
108,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,35
109,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,34
110,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,31
111,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,1,NaN,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,31
112,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,31
113,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,1,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,31
114,1,1,1,1,1,1,1,NaN,1,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,30
115,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,30
116,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,29
117,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,29
118,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,29
119,1,1,1,1,1,1,1,1,NaN,NaN,1,NaN,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,29
120,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,1,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,27
121,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,26
122,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,26
123,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,25
124,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,24
125,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,23
126,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,23
127,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,23
128,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,23
129,1,1,1,1,1,1,1,NaN,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,22
130,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,22
131,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,21
132,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,20
133,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,19
134,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,19
135,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,18
136,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,18
137,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,18
138,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,17
139,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,17
140,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,17
141,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,17
142,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,16
143,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,1,NaN,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,16
144,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,16
145,1,1,1,1,1,1,1,NaN,NaN,NaN,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,15
146,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,1,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,15
147,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,14
148,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,13
149,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,13
150,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,13
151,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,12
152,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,12
153,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,12
154,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,12
155,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,12
156,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,NaN,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,12
157,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,1,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,11
158,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,11
159,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,11
160,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,11
161,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,10
162,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,10
163,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,10
164,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,10
165,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,10
166,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,10
167,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,1,NaN,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,10
168,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,10
169,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,10
170,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9
171,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,9
172,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,9
173,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,9
174,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,1,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,9
175,1,1,1,1,1,1,1,1,NaN,NaN,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,9
176,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,9
177,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,9
178,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9
179,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,8
180,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,8
181,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,8
182,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,8
183,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,8
184,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,8
185,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,8
186,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,8
187,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,1,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,8
188,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,8
189,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,7
190,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,NaN,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,7
191,1,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,7
192,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,7
193,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,7
194,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,7
195,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,7
196,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,NaN,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,7
197,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,7
198,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,7
199,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,7
200,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,7
201,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,6
202,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,NaN,NaN,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,6
203,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,6
204,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,1,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,6
205,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,6
206,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,6
207,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,6
208,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,6
209,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,6
210,1,1,1,1,1,1,1,NaN,1,1,1,NaN,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,6
211,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,6
212,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,6
213,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,5
214,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,5
215,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,1,NaN,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,5
216,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,5
217,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,5
218,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,5
219,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,5
220,1,1,1,1,1,1,1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,5
221,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,5
222,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,5
223,1,1,1,1,1,1,1,NaN,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,5

In [52]:
imp5.impute()

Scoring Threshold             Classification                Regression
==========================================================================================
                              None                          None

Pattern: Label                Score                         Estimator
==========================================================================================

ValueError: All instances seem to have missing values.

In [155]:
reload(impyte3)
imp4 = impyte3.Impyter()

In [156]:
#imp4.impute()

In [157]:
imp4.load_data(titanic[:49])

In [158]:
_ = imp4.impute()

impyte3.py:832: UserWarning: There might be too few data points for imputation. (Threshold >= 50)

  self.clf["Classification"] = RandomForestClassifier()

Computing NaN-patterns first ...

Scoring Threshold             Classification                Regression
==========================================================================================
                              None                          None

Pattern: Label                Score                         Estimator
==========================================================================================
1: Age                        -0.072 (r2)                   RandomForestRegressor           imputed...

In [159]:
imp4.pattern()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Count
0,1,1,1,1,1,1,1,1,1,1,1,35
1,1,1,1,1,1,NaN,1,1,1,1,1,14

In [160]:
# Set threshold levels to drop
imp4.drop_imputation([.7, .5])

Dropping pattern 1 (-0.071660977498 < 0.5 r2)

In [147]:
imp4.get_result()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
5,6,0,3,"Moran, Mr. James",male,23.7,0,0,330877,8.4583,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,36.8,0,0,244373,13.0000,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,22.5,0,0,2649,7.2250,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,23.1,0,0,2631,7.2250,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,21.4,0,0,330959,7.8792,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,23.1,0,0,349216,7.8958,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,C
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,25.9,1,0,PC 17569,146.5208,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,21.4,0,0,335677,7.7500,Q
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,S
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,1,0,PC 17604,82.1708,C
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,S
36,37,1,3,"Mamee, Mr. Hanna",male,22.8,0,0,2677,7.2292,C
37,38,0,3,"Cann, Mr. Ernest Charles",male,21.0,0,0,A./5. 2152,8.0500,S
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.0,2,0,345764,18.0000,S
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,11.2417,C
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,S
41,42,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann ...",female,27.0,1,0,11668,21.0000,S
42,43,0,3,"Kraeff, Mr. Theodor",male,23.7,0,0,349253,7.8958,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,C
44,45,1,3,"Devaney, Miss. Margaret Delia",female,19.0,0,0,330958,7.8792,Q
45,46,0,3,"Rogers, Mr. William John",male,23.7,0,0,S.C./A.4. 23567,8.0500,S
46,47,0,3,"Lennon, Mr. Denis",male,17.2,1,0,370371,15.5000,Q
47,48,1,3,"O'Driscoll, Miss. Bridget",female,22.1,0,0,14311,7.7500,Q
48,49,0,3,"Samaan, Mr. Youssef",male,9.7,2,0,2662,21.6792,C

In [139]:
drop_imputation([.7, .5])

In [120]:
imp4.model_log

{}

In [109]:
imp4.model_log

{}

In [108]:
del(imp4.model_log[1])

In [100]:
mdl.get_score()

0.028740160506003386

In [95]:
mdl.get_scoring()

['r2']

In [82]:
mdl.get_threshold()

[array([ 0.29103918,  0.18253541,  0.2175669 ,  0.17002546, -1.43861987])]

In [74]:
imp4.drop_imputation([.7, .5])

In [201]:
def flight_length(minutes, movie_lengths):
    minutes_dict = set() # remainder : index
    for ml in movie_lengths:
        if ml in minutes_dict:
            return True
        minutes_dict.add(minutes - ml)
    return False

In [202]:
movie_lengths = [1, 5, 2, 3, 7, 9, 10]

In [203]:
# 11 #

In [205]:
flight_length(11, movie_lengths)

True