# Test Cases
To properly test all functions several data sets are being loaded and investigated.

In [793]:
import impyte3
import pandas as pd

In [805]:
reload(impyte3)
imp = impyte3.Impyter()

## Titanic Data
From Kaggle Titanic Data Set.

In [806]:
reload(impyte3)
imp = impyte3.Impyter()
titanic = pd.read_csv("data/testdata/titanic_data.csv", low_memory=False)
imp.load_data(titanic)

In [807]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [808]:
imp.pattern()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Count
0,1,1,1,1,1,1,1,1,1,1,NaN,1,529
1,1,1,1,1,1,1,1,1,1,1,1,1,183
2,1,1,1,1,1,NaN,1,1,1,1,NaN,1,158
3,1,1,1,1,1,NaN,1,1,1,1,1,1,19
4,1,1,1,1,1,1,1,1,1,1,1,NaN,2

In [809]:
ret = imp.impute(verbose=True, multi_nans=True)

Scoring Threshold             Classification                Regression
==========================================================================================
                              None                          None

Pattern: Label                Score                         Estimator
==========================================================================================
0: Cabin (* 1)                0.000 (f1_macro)              RandomForestClassifier          imputed...
3: Age                        0.174 (r2)                    RandomForestRegressor           imputed...
4: Embarked (* 2)             0.000 (f1_macro)              RandomForestClassifier          imputed...

Multi nans
==========================================================================================
2: Age                        0.140 (r2)                    RandomForestRegressor           imputed...
2: Cabin (* 3)                0.000 (f1_macro)              RandomForestClassifier          imputed...


* (1) Cabin: All the n_groups for individual classes are less than n_splits=5.
* (2) Embarked: The least populated class in y has only 2 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (3) Cabin: All the n_groups for individual classes are less than n_splits=5.

In [799]:
imp.model_log[0].predictor_variables

Index([u'PassengerId', u'Survived', u'Pclass', u'Name', u'Sex', u'Age',
       u'SibSp', u'Parch', u'Ticket', u'Fare', u'Embarked'],
      dtype='object')

In [800]:
imp5 = impyte3.Impyter(ret)
imp5.pattern()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Count
0,1,1,1,1,1,1,1,1,1,1,1,1,891

In [497]:
titanic.drop("Cabin", axis=1, inplace=True)

In [498]:
imp.load_data(titanic)
_ = imp.get_summary()

In [499]:
imp.pattern()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Count
0,1,1,1,1,1,1,1,1,1,1,1,712
1,1,1,1,1,1,NaN,1,1,1,1,1,177
2,1,1,1,1,1,1,1,1,1,1,NaN,2

In [500]:
imp.get_data().head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [501]:
res = imp.impute(multi_nans=True)

Scoring Threshold             Classification                Regression
==========================================================================================
                              None                          None

Pattern: Label                Score                         Estimator
==========================================================================================
1: Age                        0.226 (r2)                    RandomForestRegressor           imputed...
2: Embarked (* 1)             0.000 (f1_macro)              RandomForestClassifier          imputed...


* (1) Embarked: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.

In [502]:
res.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [503]:
imp2 = impyte3.Impyter(res)

In [504]:
imp2.pattern()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Count
0,1,1,1,1,1,1,1,1,1,1,1,891

## Sensoric Data

In [52]:
sensoric_data = pd.read_csv('data/testdata/pml-training.csv', low_memory=False)

In [53]:
reload(impyte3)
imp = impyte3.Impyter(sensoric_data)

In [54]:
summa = imp.get_summary()
summa

                          Complete  Missing Percentage  Unique
max_roll_belt                  406    19216    97.93 %     196
kurtosis_roll_forearm          406    19216    97.93 %     322
kurtosis_roll_belt             406    19216    97.93 %     397
kurtosis_picth_belt            406    19216    97.93 %     317
kurtosis_yaw_belt              406    19216    97.93 %       2
skewness_roll_belt             406    19216    97.93 %     395
skewness_roll_belt.1           406    19216    97.93 %     338
skewness_yaw_belt              406    19216    97.93 %       2
avg_yaw_dumbbell               406    19216    97.93 %     398
max_yaw_belt                   406    19216    97.93 %      68
min_roll_belt                  406    19216    97.93 %     185
min_pitch_belt                 406    19216    97.93 %      17
var_yaw_dumbbell               406    19216    97.93 %     392
stddev_yaw_dumbbell            406    19216    97.93 %     392
kurtosis_picth_forearm         406    19216    97.93 %     323
var_pitch_dumbbell             406    19216    97.93 %     392
stddev_pitch_dumbbell          406    19216    97.93 %     392
avg_pitch_dumbbell             406    19216    97.93 %     398
max_picth_belt                 406    19216    97.93 %      23
kurtosis_yaw_forearm           406    19216    97.93 %       2
min_roll_forearm               406    19216    97.93 %     270
skewness_pitch_forearm         406    19216    97.93 %     319
var_yaw_forearm                406    19216    97.93 %     323
stddev_yaw_forearm             406    19216    97.93 %     323
avg_yaw_forearm                406    19216    97.93 %     325
var_pitch_forearm              406    19216    97.93 %     325
stddev_pitch_forearm           406    19216    97.93 %     324
avg_pitch_forearm              406    19216    97.93 %     325
var_roll_forearm               406    19216    97.93 %     321
stddev_roll_forearm            406    19216    97.93 %     321
...                            ...      ...        ...     ...
stddev_yaw_belt                406    19216    97.93 %      59
avg_roll_dumbbell              406    19216    97.93 %     398
max_roll_arm                   406    19216    97.93 %     291
max_yaw_arm                    406    19216    97.93 %      52
amplitude_yaw_dumbbell         406    19216    97.93 %       3
amplitude_pitch_dumbbell       406    19216    97.93 %     384
amplitude_roll_dumbbell        406    19216    97.93 %     388
min_yaw_dumbbell               406    19216    97.93 %      73
min_pitch_dumbbell             406    19216    97.93 %     357
min_roll_dumbbell              406    19216    97.93 %     333
max_yaw_dumbbell               406    19216    97.93 %      73
max_picth_dumbbell             406    19216    97.93 %     340
max_roll_dumbbell              406    19216    97.93 %     339
skewness_yaw_dumbbell          406    19216    97.93 %       2
skewness_pitch_dumbbell        406    19216    97.93 %     402
max_picth_arm                  406    19216    97.93 %     264
skewness_roll_dumbbell         406    19216    97.93 %     401
kurtosis_picth_dumbbell        406    19216    97.93 %     401
kurtosis_roll_dumbbell         406    19216    97.93 %     398
amplitude_roll_belt            406    19216    97.93 %     149
amplitude_pitch_belt           406    19216    97.93 %      14
amplitude_yaw_belt             406    19216    97.93 %       4
amplitude_yaw_arm              406    19216    97.93 %      52
amplitude_pitch_arm            406    19216    97.93 %     295
amplitude_roll_arm             406    19216    97.93 %     307
var_total_accel_belt           406    19216    97.93 %      66
min_pitch_arm                  406    19216    97.93 %     291
min_roll_arm                   406    19216    97.93 %     279
kurtosis_yaw_dumbbell          406    19216    97.93 %       2
min_yaw_arm                    406    19216    97.93 %      39

[100 rows x 4 columns]

In [55]:
imp.pattern()

,Unnamed: 0,user_name,raw_timestamp_part_1,raw_timestamp_part_2,cvtd_timestamp,new_window,num_window,roll_belt,pitch_belt,yaw_belt,total_accel_belt,kurtosis_roll_belt,kurtosis_picth_belt,kurtosis_yaw_belt,skewness_roll_belt,skewness_roll_belt.1,skewness_yaw_belt,max_roll_belt,max_picth_belt,max_yaw_belt,min_roll_belt,min_pitch_belt,min_yaw_belt,amplitude_roll_belt,amplitude_pitch_belt,amplitude_yaw_belt,var_total_accel_belt,avg_roll_belt,stddev_roll_belt,var_roll_belt,avg_pitch_belt,stddev_pitch_belt,var_pitch_belt,avg_yaw_belt,stddev_yaw_belt,var_yaw_belt,gyros_belt_x,gyros_belt_y,gyros_belt_z,accel_belt_x,accel_belt_y,accel_belt_z,magnet_belt_x,magnet_belt_y,magnet_belt_z,roll_arm,pitch_arm,yaw_arm,total_accel_arm,var_accel_arm,avg_roll_arm,stddev_roll_arm,var_roll_arm,avg_pitch_arm,stddev_pitch_arm,var_pitch_arm,avg_yaw_arm,stddev_yaw_arm,var_yaw_arm,gyros_arm_x,gyros_arm_y,gyros_arm_z,accel_arm_x,accel_arm_y,accel_arm_z,magnet_arm_x,magnet_arm_y,magnet_arm_z,kurtosis_roll_arm,kurtosis_picth_arm,kurtosis_yaw_arm,skewness_roll_arm,skewness_pitch_arm,skewness_yaw_arm,max_roll_arm,max_picth_arm,max_yaw_arm,min_roll_arm,min_pitch_arm,min_yaw_arm,amplitude_roll_arm,amplitude_pitch_arm,amplitude_yaw_arm,roll_dumbbell,pitch_dumbbell,yaw_dumbbell,kurtosis_roll_dumbbell,kurtosis_picth_dumbbell,kurtosis_yaw_dumbbell,skewness_roll_dumbbell,skewness_pitch_dumbbell,skewness_yaw_dumbbell,max_roll_dumbbell,max_picth_dumbbell,max_yaw_dumbbell,min_roll_dumbbell,min_pitch_dumbbell,min_yaw_dumbbell,amplitude_roll_dumbbell,amplitude_pitch_dumbbell,amplitude_yaw_dumbbell,total_accel_dumbbell,var_accel_dumbbell,avg_roll_dumbbell,stddev_roll_dumbbell,var_roll_dumbbell,avg_pitch_dumbbell,stddev_pitch_dumbbell,var_pitch_dumbbell,avg_yaw_dumbbell,stddev_yaw_dumbbell,var_yaw_dumbbell,gyros_dumbbell_x,gyros_dumbbell_y,gyros_dumbbell_z,accel_dumbbell_x,accel_dumbbell_y,accel_dumbbell_z,magnet_dumbbell_x,magnet_dumbbell_y,magnet_dumbbell_z,roll_forearm,pitch_forearm,yaw_forearm,kurtosis_roll_forearm,kurtosis_picth_forearm,kurtosis_yaw_forearm,skewness_roll_forearm,skewness_pitch_forearm,skewness_yaw_forearm,max_roll_forearm,max_picth_forearm,max_yaw_forearm,min_roll_forearm,min_pitch_forearm,min_yaw_forearm,amplitude_roll_forearm,amplitude_pitch_forearm,amplitude_yaw_forearm,total_accel_forearm,var_accel_forearm,avg_roll_forearm,stddev_roll_forearm,var_roll_forearm,avg_pitch_forearm,stddev_pitch_forearm,var_pitch_forearm,avg_yaw_forearm,stddev_yaw_forearm,var_yaw_forearm,gyros_forearm_x,gyros_forearm_y,gyros_forearm_z,accel_forearm_x,accel_forearm_y,accel_forearm_z,magnet_forearm_x,magnet_forearm_y,magnet_forearm_z,classe,Count
0,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,19216
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,406

In [56]:
tmp2 = imp.pattern()

In [57]:
res = imp.impute(multi_nans=True)

Scoring Threshold             Classification                Regression
==========================================================================================
                              None                          None

Pattern: Label                Score                         Estimator
==========================================================================================

Multi nans
==========================================================================================
0: kurtosis_roll_belt (* 1)   0.000 (f1_macro)              RandomForestClassifier          imputed...
0: kurtosis_picth_belt (* 2)  0.000 (f1_macro)              RandomForestClassifier          imputed...
0: kurtosis_yaw_belt          1.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_roll_belt (* 3)   0.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_roll_belt.1 (* 4) 0.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_yaw_belt          1.000 (f1_macro)              RandomForestClassifier          imputed...
0: max_roll_belt              0.971 (r2)                    RandomForestRegressor           imputed...
0: max_picth_belt             0.931 (r2)                    RandomForestRegressor           imputed...
0: max_yaw_belt (* 5)         0.000 (f1_macro)              RandomForestClassifier          imputed...
0: min_roll_belt              0.909 (r2)                    RandomForestRegressor           imputed...
0: min_pitch_belt             0.981 (r2)                    RandomForestRegressor           imputed...
0: min_yaw_belt (* 6)         0.000 (f1_macro)              RandomForestClassifier          imputed...
0: amplitude_roll_belt        -109.093 (r2)                 RandomForestRegressor           imputed...
0: amplitude_pitch_belt       -1.230 (r2)                   RandomForestRegressor           imputed...
0: amplitude_yaw_belt (* 7)   0.000 (f1_macro)              RandomForestClassifier          imputed...
0: var_total_accel_belt       -9.885 (r2)                   RandomForestRegressor           imputed...
0: avg_roll_belt              0.987 (r2)                    RandomForestRegressor           imputed...
0: stddev_roll_belt           -0.691 (r2)                   RandomForestRegressor           imputed...
0: var_roll_belt              -2.175 (r2)                   RandomForestRegressor           imputed...
0: avg_pitch_belt             0.960 (r2)                    RandomForestRegressor           imputed...
0: stddev_pitch_belt          -0.172 (r2)                   RandomForestRegressor           imputed...
0: var_pitch_belt             -1.025 (r2)                   RandomForestRegressor           imputed...
0: avg_yaw_belt               0.972 (r2)                    RandomForestRegressor           imputed...
0: stddev_yaw_belt            -314.056 (r2)                 RandomForestRegressor           imputed...
0: var_yaw_belt               -3538437.418 (r2)             RandomForestRegressor           imputed...
0: var_accel_arm              0.327 (r2)                    RandomForestRegressor           imputed...
0: avg_roll_arm               0.859 (r2)                    RandomForestRegressor           imputed...
0: stddev_roll_arm            -0.446 (r2)                   RandomForestRegressor           imputed...
0: var_roll_arm               -5.347 (r2)                   RandomForestRegressor           imputed...
0: avg_pitch_arm              0.572 (r2)                    RandomForestRegressor           imputed...
0: stddev_pitch_arm           0.271 (r2)                    RandomForestRegressor           imputed...
0: var_pitch_arm              -0.038 (r2)                   RandomForestRegressor           imputed...
0: avg_yaw_arm                0.659 (r2)                    RandomForestRegressor           imputed...
0: stddev_yaw_arm             -0.025 (r2)                   RandomForestRegressor           imputed...
0: var_yaw_arm                -3.865 (r2)                   RandomForestRegressor           imputed...
0: kurtosis_roll_arm (* 8)    0.000 (f1_macro)              RandomForestClassifier          imputed...
0: kurtosis_picth_arm (* 9)   0.000 (f1_macro)              RandomForestClassifier          imputed...
0: kurtosis_yaw_arm (* 10)    0.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_roll_arm (* 11)   0.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_pitch_arm (* 12)  0.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_yaw_arm (* 13)    0.000 (f1_macro)              RandomForestClassifier          imputed...
0: max_roll_arm               0.536 (r2)                    RandomForestRegressor           imputed...
0: max_picth_arm              0.589 (r2)                    RandomForestRegressor           imputed...
0: max_yaw_arm                0.383 (r2)                    RandomForestRegressor           imputed...
0: min_roll_arm               0.427 (r2)                    RandomForestRegressor           imputed...
0: min_pitch_arm              0.508 (r2)                    RandomForestRegressor           imputed...
0: min_yaw_arm                0.102 (r2)                    RandomForestRegressor           imputed...
0: amplitude_roll_arm         0.321 (r2)                    RandomForestRegressor           imputed...
0: amplitude_pitch_arm        0.068 (r2)                    RandomForestRegressor           imputed...
0: amplitude_yaw_arm          0.345 (r2)                    RandomForestRegressor           imputed...
0: kurtosis_roll_dumbbell (* 14)0.000 (f1_macro)              RandomForestClassifier          imputed...
0: kurtosis_picth_dumbbell (* 15)0.000 (f1_macro)              RandomForestClassifier          imputed...
0: kurtosis_yaw_dumbbell      1.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_roll_dumbbell (* 16)0.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_pitch_dumbbell (* 17)0.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_yaw_dumbbell      1.000 (f1_macro)              RandomForestClassifier          imputed...
0: max_roll_dumbbell          0.660 (r2)                    RandomForestRegressor           imputed...
0: max_picth_dumbbell         0.857 (r2)                    RandomForestRegressor           imputed...
0: max_yaw_dumbbell (* 18)    0.000 (f1_macro)              RandomForestClassifier          imputed...
0: min_roll_dumbbell          0.330 (r2)                    RandomForestRegressor           imputed...
0: min_pitch_dumbbell         0.747 (r2)                    RandomForestRegressor           imputed...
0: min_yaw_dumbbell (* 19)    0.000 (f1_macro)              RandomForestClassifier          imputed...
0: amplitude_roll_dumbbell    0.317 (r2)                    RandomForestRegressor           imputed...
0: amplitude_pitch_dumbbell   0.371 (r2)                    RandomForestRegressor           imputed...
0: amplitude_yaw_dumbbell (* 20)0.000 (f1_macro)              RandomForestClassifier          imputed...
0: var_accel_dumbbell         -0.041 (r2)                   RandomForestRegressor           imputed...
0: avg_roll_dumbbell          0.651 (r2)                    RandomForestRegressor           imputed...
0: stddev_roll_dumbbell       0.086 (r2)                    RandomForestRegressor           imputed...
0: var_roll_dumbbell          -0.337 (r2)                   RandomForestRegressor           imputed...
0: avg_pitch_dumbbell         0.703 (r2)                    RandomForestRegressor           imputed...
0: stddev_pitch_dumbbell      0.258 (r2)                    RandomForestRegressor           imputed...
0: var_pitch_dumbbell         0.052 (r2)                    RandomForestRegressor           imputed...
0: avg_yaw_dumbbell           0.867 (r2)                    RandomForestRegressor           imputed...
0: stddev_yaw_dumbbell        0.318 (r2)                    RandomForestRegressor           imputed...
0: var_yaw_dumbbell           0.216 (r2)                    RandomForestRegressor           imputed...
0: kurtosis_roll_forearm (* 21)0.000 (f1_macro)              RandomForestClassifier          imputed...
0: kurtosis_picth_forearm (* 22)0.000 (f1_macro)              RandomForestClassifier          imputed...
0: kurtosis_yaw_forearm       1.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_roll_forearm (* 23)0.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_pitch_forearm (* 24)0.000 (f1_macro)              RandomForestClassifier          imputed...
0: skewness_yaw_forearm       1.000 (f1_macro)              RandomForestClassifier          imputed...
0: max_roll_forearm           0.598 (r2)                    RandomForestRegressor           imputed...
0: max_picth_forearm          0.526 (r2)                    RandomForestRegressor           imputed...
0: max_yaw_forearm (* 25)     0.000 (f1_macro)              RandomForestClassifier          imputed...
0: min_roll_forearm           0.145 (r2)                    RandomForestRegressor           imputed...
0: min_pitch_forearm          0.410 (r2)                    RandomForestRegressor           imputed...
0: min_yaw_forearm (* 26)     0.000 (f1_macro)              RandomForestClassifier          imputed...
0: amplitude_roll_forearm     0.318 (r2)                    RandomForestRegressor           imputed...
0: amplitude_pitch_forearm    0.369 (r2)                    RandomForestRegressor           imputed...
0: amplitude_yaw_forearm      0.996 (f1_macro)              RandomForestClassifier          imputed...
0: var_accel_forearm          -0.135 (r2)                   RandomForestRegressor           imputed...
0: avg_roll_forearm           0.411 (r2)                    RandomForestRegressor           imputed...
0: stddev_roll_forearm        0.233 (r2)                    RandomForestRegressor           imputed...
0: var_roll_forearm           0.172 (r2)                    RandomForestRegressor           imputed...
0: avg_pitch_forearm          0.509 (r2)                    RandomForestRegressor           imputed...
0: stddev_pitch_forearm       0.113 (r2)                    RandomForestRegressor           imputed...
0: var_pitch_forearm          -0.536 (r2)                   RandomForestRegressor           imputed...
0: avg_yaw_forearm            0.507 (r2)                    RandomForestRegressor           imputed...
0: stddev_yaw_forearm         0.370 (r2)                    RandomForestRegressor           imputed...
0: var_yaw_forearm            0.117 (r2)                    RandomForestRegressor           imputed...


* (1) kurtosis_roll_belt: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (2) kurtosis_picth_belt: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (3) skewness_roll_belt: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (4) skewness_roll_belt.1: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (5) max_yaw_belt: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (6) min_yaw_belt: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (7) amplitude_yaw_belt: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
* (8) kurtosis_roll_arm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (9) kurtosis_picth_arm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (10) kurtosis_yaw_arm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (11) skewness_roll_arm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (12) skewness_pitch_arm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (13) skewness_yaw_arm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (14) kurtosis_roll_dumbbell: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (15) kurtosis_picth_dumbbell: All the n_groups for individual classes are less than n_splits=5.
* (16) skewness_roll_dumbbell: All the n_groups for individual classes are less than n_splits=5.
* (17) skewness_pitch_dumbbell: All the n_groups for individual classes are less than n_splits=5.
* (18) max_yaw_dumbbell: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (19) min_yaw_dumbbell: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (20) amplitude_yaw_dumbbell: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
* (21) kurtosis_roll_forearm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (22) kurtosis_picth_forearm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (23) skewness_roll_forearm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (24) skewness_pitch_forearm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (25) max_yaw_forearm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (26) min_yaw_forearm: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.

In [58]:
imp2 = impyte3.Impyter(res)

In [59]:
imp2.pattern()

,Unnamed: 0,user_name,raw_timestamp_part_1,raw_timestamp_part_2,cvtd_timestamp,new_window,num_window,roll_belt,pitch_belt,yaw_belt,total_accel_belt,kurtosis_roll_belt,kurtosis_picth_belt,kurtosis_yaw_belt,skewness_roll_belt,skewness_roll_belt.1,skewness_yaw_belt,max_roll_belt,max_picth_belt,max_yaw_belt,min_roll_belt,min_pitch_belt,min_yaw_belt,amplitude_roll_belt,amplitude_pitch_belt,amplitude_yaw_belt,var_total_accel_belt,avg_roll_belt,stddev_roll_belt,var_roll_belt,avg_pitch_belt,stddev_pitch_belt,var_pitch_belt,avg_yaw_belt,stddev_yaw_belt,var_yaw_belt,gyros_belt_x,gyros_belt_y,gyros_belt_z,accel_belt_x,accel_belt_y,accel_belt_z,magnet_belt_x,magnet_belt_y,magnet_belt_z,roll_arm,pitch_arm,yaw_arm,total_accel_arm,var_accel_arm,avg_roll_arm,stddev_roll_arm,var_roll_arm,avg_pitch_arm,stddev_pitch_arm,var_pitch_arm,avg_yaw_arm,stddev_yaw_arm,var_yaw_arm,gyros_arm_x,gyros_arm_y,gyros_arm_z,accel_arm_x,accel_arm_y,accel_arm_z,magnet_arm_x,magnet_arm_y,magnet_arm_z,kurtosis_roll_arm,kurtosis_picth_arm,kurtosis_yaw_arm,skewness_roll_arm,skewness_pitch_arm,skewness_yaw_arm,max_roll_arm,max_picth_arm,max_yaw_arm,min_roll_arm,min_pitch_arm,min_yaw_arm,amplitude_roll_arm,amplitude_pitch_arm,amplitude_yaw_arm,roll_dumbbell,pitch_dumbbell,yaw_dumbbell,kurtosis_roll_dumbbell,kurtosis_picth_dumbbell,kurtosis_yaw_dumbbell,skewness_roll_dumbbell,skewness_pitch_dumbbell,skewness_yaw_dumbbell,max_roll_dumbbell,max_picth_dumbbell,max_yaw_dumbbell,min_roll_dumbbell,min_pitch_dumbbell,min_yaw_dumbbell,amplitude_roll_dumbbell,amplitude_pitch_dumbbell,amplitude_yaw_dumbbell,total_accel_dumbbell,var_accel_dumbbell,avg_roll_dumbbell,stddev_roll_dumbbell,var_roll_dumbbell,avg_pitch_dumbbell,stddev_pitch_dumbbell,var_pitch_dumbbell,avg_yaw_dumbbell,stddev_yaw_dumbbell,var_yaw_dumbbell,gyros_dumbbell_x,gyros_dumbbell_y,gyros_dumbbell_z,accel_dumbbell_x,accel_dumbbell_y,accel_dumbbell_z,magnet_dumbbell_x,magnet_dumbbell_y,magnet_dumbbell_z,roll_forearm,pitch_forearm,yaw_forearm,kurtosis_roll_forearm,kurtosis_picth_forearm,kurtosis_yaw_forearm,skewness_roll_forearm,skewness_pitch_forearm,skewness_yaw_forearm,max_roll_forearm,max_picth_forearm,max_yaw_forearm,min_roll_forearm,min_pitch_forearm,min_yaw_forearm,amplitude_roll_forearm,amplitude_pitch_forearm,amplitude_yaw_forearm,total_accel_forearm,var_accel_forearm,avg_roll_forearm,stddev_roll_forearm,var_roll_forearm,avg_pitch_forearm,stddev_pitch_forearm,var_pitch_forearm,avg_yaw_forearm,stddev_yaw_forearm,var_yaw_forearm,gyros_forearm_x,gyros_forearm_y,gyros_forearm_z,accel_forearm_x,accel_forearm_y,accel_forearm_z,magnet_forearm_x,magnet_forearm_y,magnet_forearm_z,classe,Count
0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,19622

In [60]:
!ls data/testdata

KaggleV2-May-2016.csv           matched_Building_Complaints.csv
customers.csv                   pml-training.csv
file_safety_complaints_fair.csv student-data.csv
housing.csv                     titanic_data.csv

In [505]:
import impyte3

In [506]:
reload(impyte3)

In [507]:
customer_data = pd.read_csv('data/testdata/file_safety_complaints_fair.csv')

In [508]:
#customer_data.drop(["Address", "Closest Address", "Location"], axis=1, inplace=True)

In [509]:
imp3 = impyte3.Impyter(customer_data[:1000])

In [510]:
imp3.pattern()

,EAS,Complaint Item Type Description,Address,Zipcode,Battalion,Station Area,Received Date,Entry Date,Disposition,Disposition Date,Neighborhood District,Location,Longitude,Latitude,LonRad,LatRad,Closest Address,Score,Count_of_complaints_per_each_EAS,Count
0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,801
1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,74
2,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,72
3,1,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,39
4,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,7
5,1,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,5
6,NaN,1,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,2

In [511]:
imp3.get_summary()

                                  Complete  Missing Percentage  Unique
Battalion                              998        2     0.20 %      11
Station Area                           993        7     0.70 %      39
EAS                                    991        9     0.90 %     431
Closest Address                        991        9     0.90 %     431
Count_of_complaints_per_each_EAS       991        9     0.90 %      21
Score                                  991        9     0.90 %      15
Disposition Date                       889      111    11.10 %     658
Disposition                            887      113    11.30 %       8

In [113]:
imp3.impute(multi_nans=True)

Scoring Threshold             Classification                Regression
==========================================================================================
                              None                          None

Pattern: Label                Score                         Estimator
==========================================================================================
1: Disposition (* 1)          0.000 (f1_macro)              RandomForestClassifier          imputed...
2: Disposition Date (* 2)     0.000 (f1_macro)              RandomForestClassifier          imputed...
5: Station Area (* 3)         0.000 (f1_macro)              RandomForestClassifier          imputed...

Multi nans
==========================================================================================
3: Disposition (* 4)          0.000 (f1_macro)              RandomForestClassifier          imputed...
3: Disposition Date (* 5)     0.000 (f1_macro)              RandomForestClassifier          imputed...
4: EAS                        0.428 (r2)                    RandomForestRegressor           imputed...
4: Closest Address (* 6)      0.000 (f1_macro)              RandomForestClassifier          imputed...
4: Score                      0.334 (r2)                    RandomForestRegressor           imputed...
4: Count_of_complaints_per_each_EAS0.751 (r2)                    RandomForestRegressor           imputed...
6: EAS                        0.422 (r2)                    RandomForestRegressor           imputed...
6: Battalion (* 7)            0.000 (f1_macro)              RandomForestClassifier          imputed...
6: Station Area (* 8)         0.000 (f1_macro)              RandomForestClassifier          imputed...
6: Closest Address (* 9)      0.000 (f1_macro)              RandomForestClassifier          imputed...
6: Score                      0.332 (r2)                    RandomForestRegressor           imputed...
6: Count_of_complaints_per_each_EAS0.753 (r2)                    RandomForestRegressor           imputed...


* (1) Disposition: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (2) Disposition Date: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (3) Station Area: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (4) Disposition: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (5) Disposition Date: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (6) Closest Address: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (7) Battalion: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
* (8) Station Area: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
* (9) Closest Address: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.

,EAS,Complaint Item Type Description,Address,Zipcode,Battalion,Station Area,Received Date,Entry Date,Disposition,Disposition Date,Neighborhood District,Location,Longitude,Latitude,LonRad,LatRad,Closest Address,Score,Count_of_complaints_per_each_EAS
0,281694.00,uncategorized complaint,460 Ellis St,94102.0,2,3,8/4/05,8/4/05,condition corrected,9/20/05,Tenderloin,"(37.7849959400297, -122.41382465)",-122.413825,37.784996,-2.136524,0.659473,460 ELLIS ST,96.0,1.0
1,304879.00,alarm systems,3215 Clement St,94121.0,7,34,10/31/11,10/31/11,condition corrected,10/31/11,Outer Richmond,"(37.7813616200296, -122.49378054)",-122.493780,37.781362,-2.137920,0.659409,3215 CLEMENT ST,97.0,3.0
2,296558.00,operating without a permit,705 Divisadero St,94117.0,5,21,1/28/13,1/28/13,condition corrected,1/28/13,Hayes Valley,"(37.7761620400297, -122.43834325)",-122.438343,37.776162,-2.136952,0.659318,705 DIVISADERO ST,97.0,1.0
3,281709.00,uncategorized complaint,372 - 376 Ellis St,94102.0,3,1,5/25/05,5/31/05,condition corrected,3/21/06,Tenderloin,"(37.7852057000297, -122.41238036)",-122.412380,37.785206,-2.136499,0.659476,376 ELLIS ST,90.0,25.0
4,403215.00,uncategorized complaint,228 Duncan St,94131.0,6,11,11/29/05,11/29/05,violation issued,11/29/05,Noe Valley,"(37.7464460500297, -122.42541757)",-122.425418,37.746446,-2.136727,0.658800,228 DUNCAN ST,96.0,17.0
5,458457.00,uncategorized complaint,843 - 855 Clay St,94108.0,1,2,1/19/06,1/19/06,violation issued,1/19/06,Chinatown,"(37.7939533600297, -122.40720213)",-122.407202,37.793953,-2.136409,0.659629,855 CLAY ST,90.0,6.0
6,345881.00,alarm systems,470 Collingwood St,94114.0,6,24,10/15/15,10/15/15,condition corrected,11/13/15,Noe Valley,"(37.7548629900296, -122.43586366)",-122.435864,37.754863,-2.136909,0.658947,470 COLLINGWOOD ST,97.0,2.0
7,281709.00,uncategorized complaint,372 - 376 Ellis St,94102.0,3,1,1/28/10,1/29/10,condition corrected,3/19/10,Tenderloin,"(37.7852057000297, -122.41238036)",-122.412380,37.785206,-2.136499,0.659476,376 ELLIS ST,90.0,25.0
8,374493.00,uncategorized complaint,1464 Davidson Ave,94124.0,10,25,10/5/12,10/5/12,violation issued,10/5/12,Bayview Hunters Point,"(37.7444246000296, -122.3889812)",-122.388981,37.744425,-2.136091,0.658764,1461 DAVIDSON AVE,91.0,3.0
9,281691.00,alarm systems,434 Ellis St,94102.0,2,3,6/5/12,6/5/12,condition corrected,6/5/12,Tenderloin,"(37.7850429700297, -122.41345523)",-122.413455,37.785043,-2.136518,0.659473,434 ELLIS ST,96.0,1.0
10,304251.00,uncategorized complaint,1541 Clement St,94118.0,7,31,2/14/14,2/14/14,condition corrected,2/14/14,Outer Richmond,"(37.7822133200297, -122.47592858)",-122.475929,37.782213,-2.137608,0.659424,1541 CLEMENT ST,97.0,2.0
11,360495.00,alarm systems,65 Dorland St,94110.0,2,7,12/1/11,12/1/11,condition corrected,12/1/11,Mission,"(37.7620309300297, -122.42527614)",-122.425276,37.762031,-2.136724,0.659072,65 DORLAND ST,96.0,1.0
12,441049.00,fire escape,1440 - 1442 Clement St,94118.0,7,31,6/29/17,6/29/17,condition corrected,1/3/07,Outer Richmond,"(37.7827289900297, -122.47487392)",-122.474874,37.782729,-2.137590,0.659433,1442 CLEMENT ST,90.0,7.0
13,458444.00,uncategorized complaint,817 - 825 Clay St,94108.0,1,2,2/8/16,2/8/16,violation issued,2/8/16,Chinatown,"(37.7940541500297, -122.40665655)",-122.406657,37.794054,-2.136399,0.659631,825 CLAY ST,90.0,4.0
14,458506.00,sprinkler/standpipe systems,678 - 692 Commercial St,94111.0,1,13,5/24/16,5/24/16,condition corrected,9/8/05,Chinatown,"(37.7942173000297, -122.40438863)",-122.404389,37.794217,-2.136360,0.659634,692 COMMERCIAL ST,95.0,13.0
15,421568.00,alarm systems,852 - 854 Clay St,94108.0,1,2,12/9/08,12/9/08,condition corrected,12/9/08,Chinatown,"(37.7942876800297, -122.40739823)",-122.407398,37.794288,-2.136412,0.659635,854 CLAY ST,90.0,9.0
16,393093.00,weeds and grass,97 Delta St,94134.0,9,44,8/8/05,8/9/05,condition corrected,7/1/16,Visitacion Valley,"(37.7180429500296, -122.40699092)",-122.406991,37.718043,-2.136405,0.658304,97 DELTA ST,96.0,3.0
17,458502.00,alarm systems,771 - 783 Clay St,94108.0,1,13,7/14/10,7/14/10,condition corrected,7/14/10,Chinatown,"(37.7941499400297, -122.40594759)",-122.405948,37.794150,-2.136387,0.659632,783 CLAY ST,90.0,6.0
18,410352.00,blocked exits,17 Edgar Ave,94112.0,9,15,4/28/11,4/28/11,condition corrected,4/28/11,Oceanview/Merced/Ingleside,"(37.7209074800296, -122.45240727)",-122.452407,37.720907,-2.137198,0.658354,17 EDGAR AVE,96.0,1.0
19,365485.00,alarm systems,436 - 438 Clementina St,94103.0,3,1,8/24/10,8/24/10,condition corrected,8/24/10,South of Market,"(37.7801204800297, -122.40493606)",-122.404936,37.780120,-2.136369,0.659387,436 CLEMENTINA ST,95.0,2.0
20,280681.00,sprinkler/standpipe systems,1271 California St,94109.0,1,41,10/8/15,10/8/15,condition corrected,1/6/16,Nob Hill,"(37.7910486800297, -122.41518597)",-122.415186,37.791049,-2.136548,0.659578,1271 CALIFORNIA ST,97.0,1.0
21,456506.00,alarm systems,28 Cyril Magnin St,94102.0,3,1,6/22/10,6/22/10,condition corrected,6/22/10,Tenderloin,"(37.7848850000297, -122.40814882)",-122.408149,37.784885,-2.136425,0.659471,28 CYRIL MAGNIN ST,97.0,2.0
22,343257.00,alarm systems,2 Diamond St,94114.0,2,6,4/20/15,4/20/15,condition corrected,5/5/15,Castro/Upper Market,"(37.7621528200296, -122.43749944)",-122.437499,37.762153,-2.136937,0.659074,2 DIAMOND ST,96.0,5.0
23,458506.00,blocked exits,678 - 692 Commercial St,94111.0,1,13,5/24/16,5/24/16,condition corrected,10/31/08,Chinatown,"(37.7942173000297, -122.40438863)",-122.404389,37.794217,-2.136360,0.659634,692 COMMERCIAL ST,95.0,13.0
24,458502.00,alarm systems,771 - 783 Clay St,94108.0,1,13,1/15/16,1/15/16,condition corrected,3/23/10,Chinatown,"(37.7941499400297, -122.40594759)",-122.405948,37.794150,-2.136387,0.659632,783 CLAY ST,90.0,6.0
25,445629.00,alarm systems,2913 - 2917 Clement St,94121.0,7,14,8/24/10,8/25/10,condition corrected,8/25/10,Outer Richmond,"(37.7815065500297, -122.49056692)",-122.490567,37.781507,-2.137864,0.659412,2917 CLEMENT ST,90.0,3.0
26,365287.00,alarm systems,744 - 746 Clementina St,94103.0,2,36,3/10/09,3/10/09,condition corrected,3/10/09,South of Market,"(37.7749434000297, -122.41149632)",-122.411496,37.774943,-2.136484,0.659297,744 CLEMENTINA ST,95.0,8.0
27,421577.00,alarm systems,1425 - 1427 Clay St,94109.0,1,41,9/25/07,9/25/07,condition corrected,2/20/08,Nob Hill,"(37.7926973300297, -122.41655056)",-122.416551,37.792697,-2.136572,0.659607,1427 CLAY ST,90.0,5.0
28,281725.00,sprinkler/standpipe systems,174 Ellis St,94102.0,3,1,8/13/15,8/13/15,condition corrected,2/14/06,Tenderloin,"(37.7856298300297, -122.40905197)",-122.409052,37.785630,-2.136441,0.659484,174 ELLIS ST,96.0,7.0
29,281730.00,alarm systems,124 - 140 Ellis St,94102.0,3,1,4/28/15,4/28/15,condition corrected,5/13/15,Tenderloin,"(37.7857238200297, -122.40851249)",-122.408513,37.785724,-2.136432,0.659485,140 ELLIS ST,90.0,6.0
30,288160.00,uncategorized complaint,1445 Eddy St,94115.0,5,5,10/9/07,10/9/07,violation issued,10/9/07,Western Addition,"(37.7813061700296, -122.43142154)",-122.431421,37.781306,-2.136831,0.659408,1445 EDDY ST,96.0,8.0
31,281709.00,alarm systems,372 - 376 Ellis St,94102.0,3,1,1/13/14,1/13/14,condition corrected,1/13/14,Tenderloin,"(37.7852057000297, -122.41238036)",-122.412380,37.785206,-2.136499,0.659476,376 ELLIS ST,90.0,25.0
32,454977.00,blocked exits,2212 - 2214 Clement St,94121.0,7,14,2/8/10,2/8/10,condition corrected,2/8/10,Outer Richmond,"(37.7823525100297, -122.48302867)",-122.483029,37.782353,-2.137732,0.659426,2214 CLEMENT ST,90.0,2.0
33,275212.00,alarm systems,60 - 64 Cypress St,94110.0,6,11,12/22/05,12/22/05,condition corrected,1/9/06,Mission,"(37.7512904700296, -122.4169495)",-122.416950,37.751290,-2.136579,0.658884,60 CYPRESS ST,95.0,1.0
34,456506.00,uncategorized complaint,28 Cyril Magnin St,94102.0,3,1,4/3/07,4/3/07,condition corrected,4/16/07,Tenderloin,"(37.7848850000297, -122.40814882)",-122.408149,37.784885,-2.136425,0.659471,28 CYRIL MAGNIN ST,97.0,2.0
35,483874.00,alarm systems,136 - 154 Mcallister St,94102.0,2,1,12/14/06,12/14/06,condition corrected,1/4/07,Tenderloin,"(37.7811264600297, -122.41449959)",-122.414500,37.781126,-2.136536,0.659405,154 MCALLISTER ST,95.0,3.0
36,286473.00,uncategorized complaint,1961 Clay St,94109.0,4,38,5/5/08,5/5/08,violation issued,5/5/08,Pacific Heights,"(37.7915820300297, -122.42518955)",-122.425190,37.791582,-2.136723,0.659588,1961 CLAY ST,96.0,8.0
37,421487.00,alarm systems,371 - 373 Columbus Ave,94133.0,1,2,8/9/05,8/10/05,condition corrected,8/12/05,Chinatown,"(37.7983818200297, -122.4078231)",-122.407823,37.798382,-2.136420,0.659706,371 COLUMBUS AVE,95.0,9.0
38,344372.00,alarm systems,115 Diamond St,94114.0,6,6,9/24/10,9/24/10,condition corrected,9/24/10,Castro/Upper Market,"(37.7604194300297, -122.43687398)",-122.436874,37.760419,-2.136927,0.659044,115 DIAMOND ST,97.0,1.0
39,304508.00,uncategorized complaint,2109 Clement St,94121.0,7,14,12/10/07,12/10/07,referred to dph,1/10/08,Outer Richmond,"(37.7819394700297, -122.48191739)",-122.481917,37.781939,-2.137713,0.659419,2109 CLEMENT ST,97.0,1.0
40,421668.00,uncategorized complaint,401 - 421 Ellis St,94102.0,2,3,7/20/05,7/22/05,condition corrected,7/27/05,Tenderloin,"(37.7846739000297, -122.41301603)",-122.413016,37.784674,-2.136510,0.659467,421 ELLIS ST,90.0,10.0
41,297504.00,uncategorized complaint,333 Divisadero St,94117.0,5,21,5/23/12,5/23/12,condition corrected,5/23/12,Haight Ashbury,"(37.7726751600297, -122.43760368)",-122.437604,37.772675,-2.136939,0.659258,333 DIVISADERO ST,97.0,1.0
42,458506.00,uncategorized complaint,678 - 692 Commercial St,94111.0,1,13,3/21/11,3/21/11,condition corrected,3/21/11,Chinatown,"(37.7942173000297, -122.40438863)",-122.404389,37.794217,-2.136360,0.659634,692 COMMERCIAL ST,95.0,13.0
43,465205.00,alarm systems,625 Douglass St,94114.0,6,24,7/18/07,7/24/07,referred to another agency,8/1/07,Noe Valley,"(37.7537507000296, -122.43858577)",-122.438586,37.753751,-2.136956,0.658927,625 DOUGLASS ST,97.0,2.0
44,281730.00,alarm systems,124 - 140 Ellis St,94102.0,3,1,5/12/15,5/12/15,condition corrected,5/13/15,Tenderloin,"(37.7857238200297, -122.40851249)",-122.408513,37.785724,-2.136432,0.659485,140 ELLIS ST,90.0,6.0
45,296779.00,uncategorized complaint,58 Clayton St,94117.0,5,21,4/29/09,4/29/09,condition corrected,4/29/09,Lone Mountain/USF,"(37.7746754200297, -122.44922365)",-122.449224,37.774675,-2.137142,0.659292,58 CLAYTON ST,96.0,1.0
46,286429.00,exit maintenance,1637 Clay St,94109.0,4,41,6/21/17,6/21/17,condition corrected,1/6/16,Nob Hill,"(37.7922251100297, -122.42010973)",-122.420110,37.792225,-2.136634,0.659599,1637 CLAY ST,96.0,1.0
47,286395.00,alarm systems,1650 Clay St,94109.0,4,41,6/7/17,6/7/17,condition corrected,6/14/17,Russian Hill,"(37.7927477400297, -122.42033565)",-122.420336,37.792748,-2.136638,0.659608,1650 CLAY ST,96.0,3.0
48,286398.00,exit maintenance,1680 Clay St,94109.0,4,41,6/7/17,6/7/17,violation issued,6/8/17,Russian Hill,"(37.7926324300297, -122.42071995)",-122.420720,37.792632,-2.136645,0.659606,1680 CLAY ST,96.0,5.0
49,462393.00,alarm systems,1720 Clay St,94109.0,4,41,9/14/16,9/14/16,condition corrected,10/14/16,Russian Hill,"(37.7925600700297, -122.42157867)",-122.421579,37.792560,-2.136660,0.659605,1720 CLAY ST,96.0,2.0
50,276168.00,uncategorized complaint,1040 Columbus Ave,94133.0,1,28,10/19/12,10/19/12,violation issued,10/19/12,North Beach,"(37.8041722400297, -122.41526239)",-122.415262,37.804172,-2.136549,0.659807,1040 COLUMBUS AVE,97.0,3.0
51,304418.00,uncategorized complaint,2011 Clement St,94121.0,7,14,6/3/10,6/3/10,condition corrected,6/3/10,Outer Richmond,"(37.7820584900297, -122.48084349)",-122.480844,37.782058,-2.137694,0.659421,2011 CLEMENT ST,97.0,2.0
52,425182.00,uncategorized complaint,1611 - 1615 Clay St,94109.0,4,41,1/28/10,1/28/10,violation issued,1/28/10,Nob Hill,"(37.7924203500297, -122.41966574)",-122.419666,37.792420,-2.136626,0.659602,1615 CLAY ST,90.0,3.0
53,292437.00,alarm systems,3014 Clay St,94115.0,4,10,12/18/05,12/30/05,condition corrected,1/25/06,Pacific Heights,"(37.7898310400297, -122.44326637)",-122.443266,37.789831,-2.137038,0.659557,3014 CLAY ST,96.0,5.0
54,365287.00,uncategorized complaint,744 - 746 Clementina St,94103.0,2,36,8/5/08,8/5/08,condition corrected,8/5/08,South of Market,"(37.7749434000297, -122.41149632)",-122.411496,37.774943,-2.136484,0.659297,744 CLEMENTINA ST,95.0,8.0
55,475938.00,blocked exits,53 - 55 Columbus Ave,94111.0,1,13,8/22/12,8/22/12,condition corrected,8/22/12,Chinatown,"(37.7959539300297, -122.40423451)",-122.404235,37.795954,-2.136357,0.659664,55 COLUMBUS AVE,95.0,6.0
56,281730.00,uncategorized complaint,124 - 140 Ellis St,94102.0,3,1,5/20/13,5/20/13,condition corrected,5/20/13,Tenderloin,"(37.7857238200297, -122.40851249)",-122.408513,37.785724,-2.136432,0.659485,140 ELLIS ST,90.0,6.0
57,277057.00,uncategorized complaint,745 Columbus Ave,94133.0,1,28,7/17/09,6/23/09,condition corrected,7/17/09,Chinatown,"(37.8015217000297, -122.41227439)",-122.412274,37.801522,-2.136497,0.659761,745 COLUMBUS AVE,97.0,1.0
58,458444.00,uncategorized complaint,817 - 825 Clay St,94108.0,1,2,10/22/10,10/22/10,violation issued,10/22/10,Chinatown,"(37.7940541500297, -122.40665655)",-122.406657,37.794054,-2.136399,0.659631,825 CLAY ST,90.0,4.0
59,485153.00,blocked exits,311 Corbett Ave,94114.0,6,24,8/11/15,8/11/15,condition corrected,11/24/15,Castro/Upper Market,"(37.7604131700297, -122.44425654)",-122.444256,37.760413,-2.137055,0.659044,311 CORBETT AVE,97.0,4.0
60,421577.00,alarm systems,1425 - 1427 Clay St,94109.0,1,41,4/28/09,4/28/09,condition corrected,4/28/09,Nob Hill,"(37.7926973300297, -122.41655056)",-122.416551,37.792697,-2.136572,0.659607,1427 CLAY ST,90.0,5.0
61,280657.00,sprinkler/standpipe systems,1351 California St,94109.0,4,41,1/25/16,1/29/16,condition corrected,2/4/16,Nob Hill,"(37.7907872700297, -122.41650834)",-122.416508,37.790787,-2.136571,0.659574,1351 CALIFORNIA ST,97.0,3.0
62,474497.00,operating without a permit,325 - 329 Columbus Ave,94133.0,1,2,4/17/12,4/17/12,condition corrected,4/17/12,Chinatown,"(37.7980744900297, -122.40749917)",-122.407499,37.798074,-2.136414,0.659701,325 COLUMBUS AVE,95.0,3.0
63,421668.00,uncategorized complaint,401 - 421 Ellis St,94102.0,2,3,9/12/08,9/12/08,violation issued,9/12/08,Tenderloin,"(37.7846739000297, -122.41301603)",-122.413016,37.784674,-2.136510,0.659467,421 ELLIS ST,90.0,10.0
64,297054.00,alarm systems,643 - 655 Divisadero St,94117.0,5,21,10/4/06,10/4/06,condition corrected,10/6/06,Hayes Valley,"(37.7756265200297, -122.43826535)",-122.438265,37.775627,-2.136951,0.659309,643 DIVISADERO ST,95.0,1.0
65,447463.00,extinguishers,897 - 899 Columbus Ave,94133.0,1,28,2/14/12,2/14/12,condition corrected,1/7/09,Russian Hill,"(37.8025563900297, -122.41370988)",-122.413710,37.802556,-2.136522,0.659779,899 COLUMBUS AVE,95.0,2.0
66,402172.00,extinguishers,135 Clipper St,94114.0,6,11,6/12/09,6/12/09,condition corrected,4/11/16,Noe Valley,"(37.7490047500296, -122.4279593)",-122.427959,37.749005,-2.136771,0.658844,135 CLIPPER ST,97.0,5.0
67,280651.00,extinguishers,1375 - 1387 California St,94109.0,4,41,9/28/10,9/28/10,condition corrected,9/28/10,Nob Hill,"(37.7907323000297, -122.41688935)",-122.416889,37.790732,-2.136578,0.659573,1375 CALIFORNIA ST,95.0,3.0
68,421569.00,uncategorized complaint,868 - 870 Clay St,94108.0,1,2,6/2/15,6/2/15,condition corrected,12/30/15,Chinatown,"(37.7942713700297, -122.40753872)",-122.407539,37.794271,-2.136415,0.659634,870 CLAY ST,90.0,4.0
69,281708.00,alarm systems,370 Ellis St,94102.0,3,1,5/23/16,5/23/16,referred to another agency,5/25/16,Tenderloin,"(37.7852160900297, -122.41229516)",-122.412295,37.785216,-2.136498,0.659476,370 ELLIS ST,96.0,12.0
70,358019.00,combustible materials,75 Dore St,94103.0,2,36,1/11/11,1/11/11,condition corrected,2/8/11,South of Market,"(37.7737408000297, -122.4125923)",-122.412592,37.773741,-2.136503,0.659276,75 DORE ST,95.0,14.0
71,471325.00,combustible materials,381 Monterey Blvd,94131.0,9,6,9/27/16,9/27/16,condition corrected,10/18/16,West of Twin Peaks,"(37.7312721200296, -122.443808)",-122.443808,37.731272,-2.137048,0.658535,381 MONTEREY BLVD,97.0,6.0
72,298288.00,uncategorized complaint,662 Clayton St,94117.0,5,12,6/8/15,6/8/15,condition corrected,9/30/15,Haight Ashbury,"(37.7690534200296, -122.44814981)",-122.448150,37.769053,-2.137123,0.659194,662 CLAYTON ST,97.0,4.0
73,483874.00,uncategorized complaint,136 - 154 Mcallister St,94102.0,2,1,1/3/07,1/3/07,violation issued,1/3/07,Tenderloin,"(37.7811264600297, -122.41449959)",-122.414500,37.781126,-2.136536,0.659405,154 MCALLISTER ST,95.0,3.0
74,425599.00,alarm systems,902 - 904 Divisadero St,94115.0,5,5,11/3/14,11/3/14,condition corrected,3/10/15,Western Addition,"(37.7779603600297, -122.43808108)",-122.438081,37.777960,-2.136948,0.659350,904 DIVISADERO ST,95.0,3.0
75,278540.00,operating without a permit,342 - 366 Columbus Ave,94133.0,1,2,2/17/15,2/18/15,condition corrected,2/18/15,North Beach,"(37.7985649000297, -122.40734823)",-122.407348,37.798565,-2.136411,0.659709,342 COLUMBUS AVE,95.0,14.0
76,288031.00,alarm systems,1652 Eddy St,94115.0,5,5,4/29/14,4/29/14,condition corrected,3/22/15,Western Addition,"(37.7812926700297, -122.43496204)",-122.434962,37.781293,-2.136893,0.659408,1652 EDDY ST,96.0,4.0
77,304879.00,roof access,3215 Clement St,94121.0,7,34,7/1/10,7/1/10,condition corrected,7/1/10,Outer Richmond,"(37.7813616200296, -122.49378054)",-122.493780,37.781362,-2.137920,0.659409,3215 CLEMENT ST,97.0,3.0
78,292687.00,alarm systems,3301 Clay St,94118.0,4,10,1/18/16,1/18/16,condition corrected,2/22/16,Presidio Heights,"(37.7888271800297, -122.44733485)",-122.447335,37.788827,-2.137109,0.659539,3301 CLAY ST,96.0,7.0
79,345048.00,alarm systems,655 Corbett Ave,94114.0,6,24,7/7/08,7/7/08,condition corrected,7/22/08,Castro/Upper Market,"(37.7564868600297, -122.44300629)",-122.443006,37.756487,-2.137034,0.658975,655 CORBETT AVE,97.0,4.0
80,281709.00,alarm systems,372 - 376 Ellis St,94102.0,3,1,11/28/05,11/28/05,condition corrected,3/21/06,Tenderloin,"(37.7852057000297, -122.41238036)",-122.412380,37.785206,-2.136499,0.659476,376 ELLIS ST,90.0,25.0
81,475938.00,blocked exits,53 - 55 Columbus Ave,94111.0,1,13,8/28/12,8/28/12,condition corrected,8/28/12,Chinatown,"(37.7959539300297, -122.40423451)",-122.404235,37.795954,-2.136357,0.659664,55 COLUMBUS AVE,95.0,6.0
82,458557.00,combustible materials,1436 - 1438 California St,94109.0,1,41,3/18/08,3/18/08,condition corrected,5/15/08,Nob Hill,"(37.7911964400297, -122.41814098)",-122.418141,37.791196,-2.136600,0.659581,1438 CALIFORNIA ST,95.0,2.0
83,302694.00,alarm systems,2346 Clement St,94121.0,7,14,10/21/08,10/22/08,condition corrected,1/2/09,Outer Richmond,"(37.7821743400296, -122.48462155)",-122.484622,37.782174,-2.137760,0.659423,2346 CLEMENT ST,97.0,1.0
84,274821.00,uncategorized complaint,301 Divisadero St,94117.0,5,21,1/9/15,1/9/15,condition corrected,1/9/15,Haight Ashbury,"(37.7723035000297, -122.43752808)",-122.437528,37.772303,-2.136938,0.659251,301 DIVISADERO ST,97.0,1.0
85,304828.00,combustible materials,3049 Clement St,94121.0,7,14,1/17/07,1/17/07,referred to dbi,2/7/07,Outer Richmond,"(37.7814362800296, -122.49211159)",-122.492112,37.781436,-2.137891,0.659410,3049 CLEMENT ST,97.0,1.0
86,278540.00,uncategorized complaint,342 - 366 Columbus Ave,94133.0,1,2,5/21/09,11/1/15,condition corrected,6/15/09,North Beach,"(37.7985649000297, -122.40734823)",-122.407348,37.798565,-2.136411,0.659709,342 COLUMBUS AVE,95.0,14.0
87,292646.00,alarm systems,3199 Clay St,94115.0,4,10,2/9/17,2/9/17,condition corrected,2/27/17,Pacific Heights,"(37.7891470800297, -122.44548508)",-122.445485,37.789147,-2.137077,0.659545,3199 CLAY ST,96.0,5.0
88,292414.00,extinguishers,3140 Clay St,94115.0,4,10,10/27/16,10/27/16,condition corrected,12/16/16,Pacific Heights,"(37.7896396800297, -122.44482976)",-122.444830,37.789640,-2.137065,0.659554,3140 CLAY ST,96.0,3.0

In [114]:
res = imp3.get_result()

In [115]:
imp4 = impyte3.Impyter(res)
imp4.pattern()

,EAS,Complaint Item Type Description,Address,Zipcode,Battalion,Station Area,Received Date,Entry Date,Disposition,Disposition Date,Neighborhood District,Location,Longitude,Latitude,LonRad,LatRad,Closest Address,Score,Count_of_complaints_per_each_EAS,Count
0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1000

In [117]:
imp4.column_to_model

{}

### Fire Cases

In [71]:
import impyte
import pandas as pd

In [72]:
imp5 = impyte3.Impyter(pd.read_csv("data/testdata/matched_Building_Complaints.csv", low_memory=False))

In [73]:
imp5.pattern()

,Unnamed: 0,Complaint Number,Date Filed,Block,Lot,Street Number,Street Name,Street Suffix,Unit,Complaint Description,Status,NOV Type,Receiving Division,Assigned Division,Date 1st NOV Issued,Date 2nd NOV Issued,Date Referred to City Attorney,Director Hearing Date,Last Inspection Date,Date Abated,Closed Date,Neighborhoods - Analysis Boundaries,Supervisor District,Zipcode,Location,Longitude,Latitude,Address,LonRad,LatRad,EAS,Closest Address,Score,Count
0,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,43965
1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,36499
2,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,21347
3,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,14857
4,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,13815
5,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,12489
6,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,7396
7,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,7120
8,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,4224
9,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,3639
10,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,3601
11,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,3470
12,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,3052
13,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,2926
14,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,2581
15,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2272
16,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1954
17,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1912
18,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1888
19,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1634
20,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1547
21,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1511
22,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1469
23,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1220
24,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1075
25,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1068
26,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1020
27,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,907
28,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,814
29,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,766
30,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,614
31,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,601
32,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,562
33,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,499
34,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,431
35,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,364
36,1,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,341
37,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,301
38,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,282
39,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,280
40,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,269
41,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,258
42,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,254
43,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,253
44,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,236
45,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,231
46,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,217
47,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,214
48,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,211
49,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,198
50,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,189
51,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,160
52,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,155
53,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,151
54,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,150
55,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,141
56,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,140
57,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,132
58,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,130
59,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,124
60,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,123
61,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,110
62,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,108
63,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,106
64,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,105
65,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,101
66,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,99
67,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,95
68,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,95
69,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,91
70,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,89
71,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,87
72,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,86
73,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,86
74,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,85
75,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,80
76,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,78
77,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,78
78,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,76
79,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,76
80,1,1,1,1,1,1,1,NaN,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,74
81,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,1,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,68
82,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,67
83,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,66
84,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,66
85,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,64
86,1,1,1,1,1,1,1,NaN,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,62
87,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,61
88,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,60
89,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,60
90,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,56
91,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,56
92,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,53
93,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,52
94,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,52
95,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,51
96,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,46
97,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,45
98,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,44
99,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,44
100,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,43
101,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,39
102,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,39
103,1,1,1,1,1,1,1,NaN,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,38
104,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,36
105,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,35
106,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,35
107,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,35
108,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,35
109,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,34
110,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,31
111,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,1,NaN,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,31
112,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,31
113,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,1,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,31
114,1,1,1,1,1,1,1,NaN,1,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,30
115,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,30
116,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,29
117,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,29
118,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,29
119,1,1,1,1,1,1,1,1,NaN,NaN,1,NaN,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,29
120,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,1,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,27
121,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,26
122,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,26
123,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,25
124,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,24
125,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,23
126,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,23
127,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,23
128,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,23
129,1,1,1,1,1,1,1,NaN,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,22
130,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,22
131,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,21
132,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,20
133,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,19
134,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,19
135,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,18
136,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,18
137,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,18
138,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,17
139,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,17
140,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,17
141,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,17
142,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,16
143,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,1,NaN,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,16
144,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,16
145,1,1,1,1,1,1,1,NaN,NaN,NaN,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,15
146,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,1,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,15
147,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,14
148,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,13
149,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,13
150,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,13
151,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,12
152,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,12
153,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,12
154,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,12
155,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,12
156,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,NaN,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,12
157,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,1,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,11
158,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,11
159,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,11
160,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,11
161,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,10
162,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,10
163,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,10
164,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,10
165,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,10
166,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,10
167,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,1,NaN,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,10
168,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,10
169,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,10
170,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9
171,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,9
172,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,9
173,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,9
174,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,1,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,9
175,1,1,1,1,1,1,1,1,NaN,NaN,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,9
176,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,9
177,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,9
178,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9
179,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,8
180,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,8
181,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,8
182,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,8
183,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,8
184,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,8
185,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,8
186,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,8
187,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,1,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,8
188,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,8
189,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,7
190,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,NaN,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,7
191,1,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,7
192,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,7
193,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,7
194,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,7
195,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,7
196,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,NaN,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,7
197,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,7
198,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,7
199,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,7
200,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,7
201,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,1,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,6
202,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,NaN,NaN,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,6
203,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,6
204,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,NaN,1,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,6
205,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,6
206,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,6
207,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,NaN,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,6
208,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,6
209,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,NaN,NaN,NaN,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,6
210,1,1,1,1,1,1,1,NaN,1,1,1,NaN,1,1,1,NaN,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,6
211,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,6
212,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,6
213,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,5
214,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,5
215,1,1,1,1,1,1,1,NaN,NaN,1,1,1,1,1,1,NaN,NaN,1,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,5
216,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,5
217,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,5
218,1,1,1,1,1,1,1,1,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,5
219,1,1,1,1,1,1,1,1,NaN,1,1,NaN,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,5
220,1,1,1,1,1,1,1,1,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,5
221,1,1,1,1,1,1,1,NaN,NaN,1,1,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,1,5
222,1,1,1,1,1,1,1,1,NaN,1,1,1,1,1,1,1,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,5
223,1,1,1,1,1,1,1,NaN,1,1,1,NaN,1,1,NaN,NaN,NaN,NaN,1,NaN,NaN,1,1,1,1,1,1,1,1,1,1,1,1,5

In [52]:
imp5.impute()

Scoring Threshold             Classification                Regression
==========================================================================================
                              None                          None

Pattern: Label                Score                         Estimator
==========================================================================================

ValueError: All instances seem to have missing values.

In [580]:
reload(impyte3)
imp4 = impyte3.Impyter()

In [581]:
#imp4.impute()

In [582]:
imp4.load_data(titanic[:49])

In [583]:
res = imp4.impute(threshold=[.5, .5])

impyte3.py:913: UserWarning: There might be too few data points for imputation. (Threshold >= 50)

  self._print_header(threshold)

Computing NaN-patterns first ...

Scoring Threshold             Classification                Regression
==========================================================================================
                              0.5                           0.5

Pattern: Label                Score                         Estimator
==========================================================================================
1: Age                        -0.138 (r2)                   RandomForestRegressor           not imputed...

In [584]:
imp6 = impyte.Impyter(res)

In [585]:
imp6.pattern()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Count
0,1,1,1,1,1,1,1,1,1,1,1,35
1,1,1,1,1,1,NaN,1,1,1,1,1,14

In [586]:
imp4.pattern()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Count
0,1,1,1,1,1,1,1,1,1,1,1,35
1,1,1,1,1,1,NaN,1,1,1,1,1,14

In [587]:
#imp4.get_result()

In [588]:
# Set threshold levels to drop
imp4.drop_imputation([.7, .5], verbose=True)

Dropping pattern 1 (-0.138213734149 < 0.5 r2)

In [589]:
imp4.pattern()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Count
0,1,1,1,1,1,1,1,1,1,1,1,35

In [590]:
imp4.get_result()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,Q
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,C
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,S
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,1,0,PC 17604,82.1708,C
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,S
37,38,0,3,"Cann, Mr. Ernest Charles",male,21.0,0,0,A./5. 2152,8.0500,S
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.0,2,0,345764,18.0000,S
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,11.2417,C
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,S
41,42,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann ...",female,27.0,1,0,11668,21.0000,S
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,C
44,45,1,3,"Devaney, Miss. Margaret Delia",female,19.0,0,0,330958,7.8792,Q

In [591]:
import numpy as np
# test_data_sets

# test data building blocks

df_non_nan = [complete_list for x in range(15)]

df_all_single_nan = []
for i in range(15):
    df_all_single_nan.append(complete_list)
    df_all_single_nan.append(single_nan_list_pattern_1)
    df_all_single_nan.append(single_nan_list_pattern_3)
    df_all_single_nan.append(single_nan_list_pattern_2)

In [592]:
import numpy as np
import random
def build_test_set(complete=0, spat1=0, spat2=0, spat3=0, mpat1=0, mpat2=0, mpat3=0, allnan=0, seed=23):
    """
    Returns testing set with nan-values. Simplifies the testing procedure. 
    Limits itself to three columns. The third column is always a random continuous variable.
    
    Parameters
    ----------
    complete: int - how many complete rows should the testing set have.
    spat1: int - how many rows with pattern [np.nan, 1, 1]
    spat2: int - how many rows with pattern [1, np.nan, 1]
    spat3: int - how many rows with pattern [1, 1, np.nan]
    mpat1: int - how many rows with pattern [np.nan, np.nan, 1]
    mpat2: int - how many rows with pattern [np.nan, 1, np.nan]
    mpat3: int - how many rows with pattern [1, np.nan, np.nan]
    allnan: int - how many rows with pattern [np.nan, np.nan, np.nan]

    Returns
    -------
    pd.DataFrame with NaN-pattern overview
    """
    random.seed(seed)
    attrs_name = ["complete", "spat1", "spat2", "spat3", "mpat1", "mpat2", "mpat3", "allnan"]
    attrs = [complete, spat1, spat2, spat3, mpat1, mpat2, mpat3, allnan]
    building_blocks = {}
    building_blocks["complete"] = [1, 1, random.random()]
    building_blocks["spat1"] = [np.nan, 1, random.random()]
    building_blocks["spat2"] = [1, np.nan, random.random()]
    building_blocks["spat3"] = [1, 1, np.nan]

    building_blocks["mpat1"] = [np.nan, np.nan, random.random()]
    building_blocks["mpat2"] = [np.nan, 1, np.nan]
    building_blocks["mpat3"] = [1, np.nan, np.nan]
    building_blocks["allnan"] = [np.nan, np.nan, np.nan]

    ret_set = []
    
    for idx, attr in enumerate(attrs):
        for i in range(attr):
            tmp_block = list(building_blocks[attrs_name[idx]])
            if attrs_name[idx] in ["complete", "spat1", "spat2", "mpat1"]:
                tmp_block[2] = random.random()
            ret_set.append(tmp_block)
    return ret_set

In [593]:
test_cases = {}

In [594]:
df_all_complete = build_test_set(complete=50)

In [595]:
df_all_nan = build_test_set(allnan=50)

In [596]:
test_cases['df_complete'] = build_test_set(complete=50)

In [597]:
test_cases['df_single_nan_one_pattern'] = build_test_set(complete=50, spat1=40)

In [598]:
test_cases['df_single_nan_two_pattern'] = build_test_set(complete=50, spat1=40, spat2=30)

In [599]:
test_cases['df_single_nan_three_pattern'] = build_test_set(complete=50, spat1=40, spat2=30, spat3=20)

In [600]:
test_cases['df_multi_nan_one_pattern'] = build_test_set(complete=50, mpat1=40)
test_cases['df_multi_nan_two_pattern'] = build_test_set(complete=50, mpat1=40, mpat2=30)
test_cases['df_multi_nan_three_pattern'] = build_test_set(complete=50, mpat1=40, mpat2=30, mpat3=20)

In [601]:
test_cases['df_multi_nan_three_pattern_single_nan_three'] = build_test_set(
    complete=50, mpat1=40, mpat2=30, mpat3=20, spat1=40, spat2=30, spat3=20)

In [602]:
imp7.load_data(test_cases['df_multi_nan_three_pattern_single_nan_three'])

In [603]:
imp7.pattern()

     0    1    2  Count
0    1    1    1     50
1  NaN  NaN    1     40
2  NaN    1    1     40
3  NaN    1  NaN     30
4    1  NaN    1     30
5    1    1  NaN     20
6    1  NaN  NaN     20

In [604]:
reload(impyte3)

In [605]:
"""
for testcase in test_cases.keys():
    print("Performing Testcase: {}\n".format(testcase))
    imp7 = impyte3.Impyter(test_cases[testcase])
    print(imp7.pattern())
    res = imp7.impute(multi_nans=True)
    imp7.load_data(res)
    print(imp7.pattern())
    print("\n\n")
"""

'\nfor testcase in test_cases.keys():\n    print("Performing Testcase: {}\n".format(testcase))\n    imp7 = impyte3.Impyter(test_cases[testcase])\n    print(imp7.pattern())\n    res = imp7.impute(multi_nans=True)\n    imp7.load_data(res)\n    print(imp7.pattern())\n    print("\n\n")\n'

In [606]:
imp7 = impyte3.Impyter(test_cases['df_multi_nan_three_pattern_single_nan_three'])

In [607]:
imp7.pattern()

     0    1    2  Count
0    1    1    1     50
1  NaN  NaN    1     40
2  NaN    1    1     40
3  NaN    1  NaN     30
4    1  NaN    1     30
5    1    1  NaN     20
6    1  NaN  NaN     20

In [767]:
pattern_log = impyte3.Pattern()

In [768]:
pd.DataFrame(test_cases['df_multi_nan_three_pattern_single_nan_three'])[2].dtypes

dtype('float64')

In [769]:
pattern_log._is_discrete(pd.DataFrame(test_cases['df_multi_nan_three_pattern_single_nan_three'])[2], 3)

False

In [770]:
imp7.pattern_log.get_continuous()

[2]

In [771]:
imp7.pattern_log.get_discrete()

[0, 1]

In [772]:
len(imp7.get_data())

230

In [773]:
reload(impyte3)
imp7 = impyte3.Impyter(test_cases['df_multi_nan_three_pattern_single_nan_three'])
_ = imp7.impute(multi_nans=True)

Computing NaN-patterns first ...

Scoring Threshold             Classification                Regression
==========================================================================================
                              None                          None

Pattern: Label                Score                         Estimator
==========================================================================================
2: 0                          1.000 (f1_macro)              RandomForestClassifier          imputed...
4: 1                          1.000 (f1_macro)              RandomForestClassifier          imputed...
5: 2                          -0.318 (r2)                   RandomForestRegressor           imputed...

Multi nans
==========================================================================================
1: 0                          1.000 (f1_macro)              RandomForestClassifier          imputed...
1: 1                          1.000 (f1_macro)              RandomForestClassifier          imputed...
3: 0                          1.000 (f1_macro)              RandomForestClassifier          imputed...
3: 2                          -0.350 (r2)                   RandomForestRegressor           imputed...
6: 1                          1.000 (f1_macro)              RandomForestClassifier          imputed...
6: 2                          -0.281 (r2)                   RandomForestRegressor           imputed...

In [823]:
from collections import Counter
def map_model_to_pattern(mdl):
    pred_variables = mdl.get_predictor_variables()
    feature = mdl.get_feature_name()
    pattern_no = None
    def compare_features(list1, list2):
        return Counter(list1) == Counter(list2)

    for i in imp7.pattern_log.store_tuple_columns:
        if compare_features(feature, imp7.pattern_log.store_tuple_columns[i]):
            pattern_no = imp7.pattern_log.tuple_counter_dict[i]
            break
    if pattern_no and compare_features(pred_variables, imp7.pattern_predictor_dict[pattern_no]):
        return pattern_no
    else:
        return None

In [824]:
imp7.pattern_predictor_dict

{1: Int64Index([2], dtype='int64'),
 2: Int64Index([1, 2], dtype='int64'),
 3: Int64Index([1], dtype='int64'),
 4: Int64Index([0, 2], dtype='int64'),
 5: Int64Index([0, 1], dtype='int64'),
 6: Int64Index([0], dtype='int64')}

In [825]:
mdl = imp.get_model(0)

In [826]:
mdl2 = imp7.get_model(6)

In [828]:
map_model_to_pattern(mdl2)

6

In [822]:
mdl.get_predictor_variables()

Index([u'PassengerId', u'Survived', u'Pclass', u'Name', u'Sex', u'Age',
       u'SibSp', u'Parch', u'Ticket', u'Fare', u'Embarked'],
      dtype='object')

In [764]:
imp7.pattern_log.store_tuple_columns

{(1, 1, 1): [],
 (1, 1, 'NaN'): [2],
 (1, 'NaN', 1): [1],
 (1, 'NaN', 'NaN'): [1, 2],
 ('NaN', 1, 1): [0],
 ('NaN', 1, 'NaN'): [0, 2],
 ('NaN', 'NaN', 1): [0, 1]}

In [755]:
mdl.get_estimator_name()

['RandomForestClassifier', 'RandomForestRegressor']

In [706]:
imp7.pattern_log.tuple_counter_dict[(1, 'NaN', 'NaN')]

6

In [538]:
mdl = imp7.get_model(2)

In [551]:
mdl.get_feature_name()

0

In [539]:
mdl.get_predictor_variables()

Int64Index([1, 2], dtype='int64')

In [453]:
len(imp7.get_data())

230

In [454]:
len(imp7.get_result())

230

In [455]:
imp7.drop_imputation([1.1, 1.1])

Dropping pattern 1 (1.0 < 1.1 f1_macro)
Dropping pattern 2 (1.0 < 1.1 f1_macro)
Dropping pattern 3 (-0.291064625802 < 1.1 r2)
Dropping pattern 4 (1.0 < 1.1 f1_macro)
Dropping pattern 5 (-0.315223479267 < 1.1 r2)
Dropping pattern 6 (-0.256045719354 < 1.1 r2)

In [456]:
len(imp7.data)

230

In [457]:
len(imp7.get_result())

50

In [458]:
res = imp7.get_result()

In [459]:
imp7.load_data(res)

In [460]:
imp7.pattern()

   0  1  2  Count
0  1  1  1     50

In [461]:
imp7.pattern_log.continuous_variables

[2]

In [462]:
df_all_nan = build_test_set(allnan=50)

In [463]:
df_complete = build_test_set(complete=50)

In [464]:
df_single_nan_one_pattern = build_test_set(complete=50, spat1=40)

In [465]:
df_single_nan_two_pattern = build_test_set(complete=50, spat1=40, spat2=30)

In [466]:
df_single_nan_three_pattern = build_test_set(complete=50, spat1=40, spat2=30, spat3=20)

In [467]:
df_multi_nan_one_pattern = build_test_set(complete=50, mpat1=40)
df_multi_nan_two_pattern = build_test_set(complete=50, mpat1=40, mpat2=30)
df_multi_nan_three_pattern = build_test_set(complete=50, mpat1=40, mpat2=30, mpat3=20)
df_multi_nan_three_pattern_single_nan_three = build_test_set(
    complete=50, mpat1=40, mpat2=30, mpat3=20, spat1=40, spat2=30, spat3=20)